### ISSUE TITLE
Unable to insert into a table using Azure mobile services

### ISSUE THREAD

**Issue by SimonBowyer** [phonegap/phonegap-app-developer#105]
Trying to use the debugger for the first time. Got connected ok and looks like it will be really useful. But run into a couple of issues.

First, we check the network connection type using the following line
   networkState = navigator.connection.type;

but connection is unassigned.

Secondly, we are trying to connect to an Azure table using the following but get an error "Unexpected connection failure" in the error callback from insert().

We get an Azure client as follows:
   client = new WindowsAzure.MobileServiceClient(AzureServices.GetMobileServiceURL(), AzureServices.GetApplicationKey());

Then we insert into a table that runs a script and this is the line that ends up in the failure callback. Additionally, the JSON.parse may not be working - I displayed the error with alert() in the end as the app appeared to just hang.

accountsTable.insert({ username: userName, password: password, ConfirmationCode: confirmationCode }, { confirm: true }).then(function (results) { success code here }, function (error) {
self.failureCallback(JSON.parse(error.request.responseText).Error);
});

Thanks

**Comment by surajpindoria** [comment]
Closing this out, reported with an old version of the CLI, App, and Plugins
