### ISSUE TITLE
Method to clear localstorage

### ISSUE THREAD

**Issue by Doehl** [phonegap/phonegap-app-developer#110]
We need a simpel way of cleaning the localstorage.
At the moment is the localstorage saved, even after the App has been shotdown.

It will be nice to have a quick and easy way of clearing the localstorage, that the developing app has saved.

**Comment by patrickhofer** [comment]
+1

**Comment by jlchereau** [comment]
+1

**Comment by carol-braileanu** [comment]
+1

**Comment by notflip** [comment]
I'm wondering, since phonegap opens a browser window in the background, If i erase my android chrome browsing data, is my phonegap data gone?
