### ISSUE TITLE
Unable to access filesystem api

### ISSUE THREAD

**Issue by hi-im-si** [phonegap/phonegap-app-developer#115]
I have a phonegap application which accesses the camera api fine but after taking a photo and serving the image to my page, the filepath does not exist - it seems that the phonegap developer app is unable to access the filesystem. Any thoughts?

**Comment by timkim** [comment]
We have finally fixed this problem with the 1.5.2 release! You should now be able to access the file uri using the `PhoneGap Developer App`.
