### ISSUE TITLE
Undefined object when trying to use navigator.camera.getPicture

### ISSUE THREAD

**Issue by SimonBowyer** [phonegap/phonegap-app-developer#116]
Using the developer app, I'm getting an 'undefined' error when executing the following code:

navigator.camera.getPicture(onPhotoURISuccess, onCameraFail, { quality: 50, sourceType: 1, destinationType: destinationType.FILE_URI, encodingType: 0, targetWidth: 3264, targetHeight: 2448, saveToPhotoAlbum: true });

DetinationType is set on device ready as follows:

        destinationType = navigator.camera.DestinationType;

**Comment by mwbrooks** [comment]
Closing since we haven't see very much activity on this issue and the camera plugin has seen many updates since mid-2014.
