### ISSUE TITLE
Connection to iOS device is extremely temperamental

### ISSUE THREAD

**Issue by andycorm** [phonegap/phonegap-app-developer#120]
I've updated phonegap to version 3.4.0-0.19.21 and just downloaded the app a few days ago, and have so far found it extremely temperamental when trying to connect to the server running on my macbook. (Just to clarify, by server, I mean the product of a "phonegap serve" command, not some internal virtual server.) 95% of the time I hit 'connect' I get timeout errors, but there have been a few cases where I will just sit there, hitting connect time-after-time, and EVENTUALLY it finally does connect, without me changing any options at all.

Any idea what could be causing this? I thought maybe my iphone was opting for a cellular connection instead of my wifi, but I disabled cellular data, double and triple checked I'm on the same WiFi network as my macbook, disabled my macbook's firewall, but still no dice. Frustrating =(

**Comment by mwbrooks** [comment]
Closing since we haven't seen activity on this issue. Feel free to reopen it.
