### ISSUE TITLE
Integrate with PG CLI to support custom/3rd party plugins and multiple live devices.

### ISSUE THREAD

**Issue by tohagan** [phonegap/phonegap-app-developer#127]
Allow devs to perform a 'debug' prepare as part of the Cordova/PG CLI that does the following:

* Via the CLI, creates a new build of *this app* based on their project selected plugins for each added platform. It may also create platform specific (merged) www folders that where possible use symlinks to the root www/ and merge/ content to avoid future file copying (Yes ... Windows NTFS does symlinks and hardlinks too :) .

* Developers now deploy the new app once to their devices or simulators with all their required PG plugins.
 
* Via the CLI run a single app server instance that allows *any number* of devices and mobile OS versions to connect, loads their OS specific HTML5 app and then continues to auto reload any touched files. Client sends it's OS type to server to select the right platform folder. 

* Allow the developer to modify JS/HTML/CSS/font/image files in the root www or merge folders and via the symlinks ensure that platform versions are always maintained in sync (no need to run 'prepare' or 'compile' or to redeploy debug builds of the app to devices unless the plugins change!).

*Developer Nirvana*: Devs can now update any JS/HTML/CSS/font/image file in root www or merge folders and immediately watch the change on all the devices and OS versions sitting on their desk. I think this would be a Holy Grail that would significantly speed up app development. 

I think this would also position Cordova/PG as a significantly faster RAD tool than current native build options (even if you're only coding for one platform) as it entirely skips the Compile/Deploy phase from the development cycle and allows devs to immediately assess the impact of every change on their test devices.

**Comment by surajpindoria** [comment]
Closing this issue. The app can handle multiple devices and 3rd party plugins. Use [these](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins) instructions for adding plugins.
