### ISSUE TITLE
FileTransfer() problem

### ISSUE THREAD

**Issue by Alexandre17220** [phonegap/phonegap-app-developer#134]
Hi,

Very nice tool, but there is a problem with filetransfert.support
If you make :
alert("1");
var ft = new FileTransfer();
alert("2");
And test it it the tool, "2" is never show.
But if you use build.phonegap all are ok.

Thanks,

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
