### ISSUE TITLE
Add a QR code URL reader - Jeez I'm getting lazy.

### ISSUE THREAD

**Issue by tohagan** [phonegap/phonegap-app-developer#142]
* Add a Barcode reader plugin to read the server URL. 
* Modify the server to display the URL QR code on start up to include the server's IP address (should be configurable on the phonegap server in case we have multiple IPs).

Thanks for making my day lazier with this very cool app - with a QR code reader I can spend even more time chatting in the coffee room ;) .

**Comment by mwbrooks** [comment]
Closing this issue. At the moment, we have plans to add QR Code support. We can reopen the issue if this changes in the future.
