### ISSUE TITLE
No Audio with Media Capture Plugin

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#172]
See #158 

iOS:
- device mobile-spec: works
- served mobile-spec: __does not work__ Audio works but image is blank.

Android:
- device mobile-spec: __untested__
- served mobile-spec: __does not work__ No audio. Image capture hangs after taking a photo.

WP:
- device mobile-spec: works
- served mobile-spec: __does not work__ Audio works but image is blank `/CapturedImagesCache/WP_...`

**Comment by timkim** [comment]
These issues have been fixed with the 1.5.2 release.

**Comment by dooderlani** [comment]
I am having issues hearing any sound with my jellybean device using the phonegap developer app. I have tested on other androids and it works great...are there any known issues?
