### ISSUE TITLE
File Transfer Plugin Cannot Access Filepath

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#173]
See #153 

iOS:
- device mobile-spec: works
- served mobile-spec: __does not work__ cannot display file at `file://var/mobile/Applications/SHA/tmp/image.gif`

Android:
- device mobile-spec: works
- served mobile-spec: __does not work__ cannot display file at `file:///storage/emulated/0/Android/data/com.phonegap.whatever/cache/image.gif`

WP:
- device mobile-spec: works
- served mobile-spec: __does not work__ cannot display file at `http://10.0.1.4:3000/tmp/feather-small.gif`

**Comment by ngcl8** [comment]
Hi,

I have the same problem. Unable to use uri to show the saved images.

Cheers,
Andy

**Comment by timkim** [comment]
This has been fixed with the 1.5.2 release.
