### ISSUE TITLE
No Picture returned from the Camera Plugin

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-app-developer#174]
On all platforms, when launching the camera app via the camera plugin, a user is able to take a picture using the camera plugin but the picture is unaccessible to the app. This relates to the same origin policy error where we are attempting to access the file uri where the picture lives from a different origin.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Comment by atuttle** [comment]
I'm not sure if what I'm experiencing is related to this or not...

I'm using the PG Developer app to test my app before jumping through the hoops of compiling it on its own. In both Android and iOS I'm able to choose photos from the camera roll and view them in my app.

Then I would like to upload them to my server. On Android this is working as expected. On iOS it appears that nothing is sent. 

Via console.log I can see that the file uri (on ios) is `file:///var/mobile/Containers/Data/Application/2D778ACD-42EA-43AE-A644-FAB48855DB19/tmp/cdv_photo_003.jpg`

Here's my upload code:

	var FT = new FileTransfer();
	var uploadOptions = new FileUploadOptions();
	var uploadPath = api.baseurl + '/photos.json';

	uploadOptions.fileKey = 'photo';
	uploadOptions.fileName = 'photo.jpg';
	uploadOptions.chunkedMode = false;
	uploadOptions.params = {
		deviceId: app.info.device_id
		,latitude: lat
		,longitude: lng
		,caption: caption
	};

	var win = function(resp){ //resp is a FileUploadResult
		console.log(resp);
		$.mobile.loading('hide');
		return successCB(resp);
	};
	var lose = function(err){
		console.error(err);
		$.mobile.loading('hide');
		ui.fail_handler(err, 'photo upload');
		return failCB(err);
	};

	try {
		$.mobile.loading('show',{
			text: "Uploading photo, please wait...",
			textVisible: true,
			theme: "a"
		});
		FT.upload(fileURI, encodeURI(uploadPath), win, lose, uploadOptions);
	}catch(e){
		ui.fail_handler(e, 'calling FT.upload');
	}

If this is a known issue with the PGD app, and given that it works on Android, if I can expect it to work on iOS once compiled to my own app, then I can live with that. Is that the case?

**Comment by timkim** [comment]
Hi @atuttle 

I don't believe this is a known issue within the PhoneGap Developer App. It _should_ work once you switch over to your own compiled app. However I would look at the server logs first to see at least the app had tried to upload the image. 

If you can see maybe a 404 or at least any status code that indicated that the app tried to reach the server, that'd be a good place to start. Otherwise, if there is no indication then we can dig into this issue further.

**Comment by atuttle** [comment]
Thinking it might be the size of the uploaded file I tried uploading a screen shot of my iPod instead of a photo, but the same thing happens.

I can see that the request from iOS is sent to my server, but the server is complaining that the file field from the upload is missing/blank; which is a bit odd as I can see it listed as a field when debugging and it has a nonzero length... What baffles me is that it's the same code running on both iOS and Android, and it works fine from Android. This leads me to believe it's not the server-side code but something with the app / permissions to send the file, maybe?

**Comment by atuttle** [comment]
To follow up, after I started building my app on its own, the problem went away. I don't know what plugins the phonegap developer app has installed, but I'm making use of FileTransfer and the File plugin. I could see how not having one or both of those could be problematic. At any rate, I'm on my feet. Thanks for your attention! 👍

**Comment by timkim** [comment]
Hi @atuttle 

Well, glad to hear it's working for you!
