### ISSUE TITLE
ajax calls fail with Phonegap serve

### ISSUE THREAD

**Issue by seme1** [phonegap/phonegap-app-developer#175]
I also have a problem with ajax calls. The request's status is simply "Pending" as viewed by the "Network" tab of Weinre. The code I am using is also very simple.

``` javascript
$$.ajax({ method: 'GET', url: domainURL  ,processData: true, data:dataToSend,dataType: "json",
           success: function (data) {
            alert(data);
           }, error: function (data){
            alert("error") ;
            alert(data);
         }  });
```

I am using `Phonegap serve` to run the app containing the above code. The implementation of ajax I used is that of Jquery and also Framework7. Their ajax calls work perfectly fine in the desktop pc browser, in my mobile devices browsers (including Safari and Chrome), but NOT when built with `Phonegap serve`. I am testing on iPhone and iPad.

I am using version 3.5.0-0.20.4 of phonegap

**Comment by mwbrooks** [comment]
@guizero pull request #103 has helped to further address this issue.

Can you try updating to `phonegap@4.1.2-0.22.11` to see if it helps you out?

**Comment by timwasson** [comment]
I'm on phonegap 4.2.0-0.23.0, and I am still having this issue.

**Comment by robsonselzelin** [comment]
Hi @timwasson,

Can you detail your ajax call? Is it POST or GET? Is it over SSL?

**Comment by israelidanny** [comment]
I'm having this problem too. Mysterious and very annoying.

**Comment by seanwash** [comment]
I'm also having this issue.

Backbone, phonegap 4.1.2-0.22.9, cordova 4.0.0

POST, SSL

**Comment by seanwash** [comment]
FWIW I just tried the app via `phonegap run ios --emulator` and the ajax request is working fine. It only happens when using `phonegap serve`.

**Comment by andfaulkner** [comment]
I'm having the same problem on Android: using phonegap serve -p 3001, then running the app on the Phonegap Developer App (on a Samsung Galaxy S5) causes all AJAX requests to fail; whereas with 'cordova run android', the AJAX works just fine.

Strangely, as long as I'm not using AJAX for logging in to a server, the requests work fine: both for locally hosted files and for cross-domain requests. Failed login attempts also work just fine on the phonegap developer app: it inserts the remote hosted 'wrong password' page into the <div> tag where the loaded page is intended to go.

I'd rather not repeatedly build the app for testing: it's just too slow.

I have a guess as to the problem: it may be using the device browser without any Cordova-specific WebView settings loaded when the Phonegap Developer app is used; whereas the apk may use a sort of 'sandboxed' WebView that's a separate instance from the browser? I may try the Crosswalk Project standardized Android WebView plugin as a potential fix if this is the issue. Any validity to that?

And any further developments with this bug? It's definitely still present in Cordova/Phonegap.

**Comment by pvin** [comment]
Ajax POST request from phonegap to server fails. any idea to solve? or any other way to workaround? 
i use phonegap 4.2.0-0.24.2.

**Comment by seanwash** [comment]
I just noticed this in the `phonegap serve` logs:

http://cl.ly/image/3U1C06063A0w/Image%202015-03-23%20at%209.53.46%20AM.png

It looks like maybe the ajax urls are getting encoded?

**Comment by atuttle** [comment]
I was running into this issue today and suspected that the proxy was failing because my AJAX url was using SSL. I converted to non-SSL to confirm, and that did indeed fix it. If SSL support is intended, this ticket should be re-opened.

![image](https://cloud.githubusercontent.com/assets/46990/7032349/1e24819c-dd40-11e4-8257-5e4eaf987837.png)

![image](https://cloud.githubusercontent.com/assets/46990/7032358/31fec57e-dd40-11e4-8d4e-56393029a8fe.png)

**Comment by lnzero1** [comment]
Have the same issue with https. 
It looks like the transformation of the target url is not going to happen correctly.
From the developer tools i got this information. It seems that in the response-header, the base URL is submitted even twice ?!


```General:
Remote Address:127.0.0.1:3000
Request URL:http://localhost:3000/proxy/https%3A%2F%2F....
Request Method:POST
Status Code:302 Moved Temporarily

Response-Header:
connection:close
content-length:0
content-type:text/plain
date:Mon, 13 Apr 2015 22:45:51 GMT
location:http://undefined/proxy/https://sub.name.tldhttps://sub.name.tld/restDerURL
set-cookie:...; Path=/...; Secure; HttpOnly```

**Comment by robsonselzelin** [comment]
Is the SSL certificate self signed?

**Comment by atuttle** [comment]
Mine is not

**Comment by robsonselzelin** [comment]
Well, maybe there is a problem with phonegap serve's proxy over HTTPS protocol...

**Comment by lenichols** [comment]
How is this issue closed with no resolution... my ajax calls aren't working suddenly. I am using a POST request to send data to a C# service. Works perfectly in the web browser but not in ios with 8.2 sdk... please help. 7.1 works fine but not the current sdk.

**Comment by jeewanaryal2012** [comment]
I am having the same issue like lenichols mentioned above. It works fine in browsers but failed in device. I am using Cordova 3.8 and iOS 7 - iOS 8. Please resolve this issue.

**Comment by ccoenen** [comment]
if you are ending up here via google, and all your XHRs are turning up as 404, you _may_ be looking for this: https://github.com/apache/cordova-plugin-whitelist

**Comment by fbartolom** [comment]
I have the same problem: I wrote a script that works fine when accessed from a normal web server, but that once called in the Phonegap environment tries to access a mangled version of the one submitted(http://materiali.c-s-m.it/phonegap/), as I could see from the Chrome debug:
http://undefined/proxy/http://materiali.c-s-m.ithttp://materiali.c-s-m.it/phonegap/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED

**Comment by grippstick** [comment]
Not sure why this is closed. There has been no resolution and it is still a problem.

When using the default hello world template that is created in phonegap desktop, you cannot create a cors request. It has the whitelist included and allows *, so there should be no restrictions.

It serves from a local URL of 10.50.3.64:3000.

When I execute a basic get with the following vanilla JS:
`            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (xhttp.readyState == 4 && xhttp.status == 200) {
                    console.warn('DONE');
                } else if (xhttp.readyState == 4 && xhttp.status !== 200) {
                    console.error('DEAD');
                }
            };
            xhttp.open("GET", "https://aligntoday.com", true);
            xhttp.send();`

It errors with a 404 not found because it changes the request URL to : http://10.50.3.64:3000/proxy/https%3A%2F%2Faligntoday.com 

Any ideas how to make it stop altering my URL?

**Comment by MikhailRoot** [comment]
some helpfull info http://stackoverflow.com/questions/39097721/how-fix-or-disable-proxy-in-phonegap I've thought i need to disable proxy but in my case I just needed to supply full URL for my API.
I've created Settings var in www/js/index.js and supplied my scripts full URL like http://myhost.local
also temproarily disabled CSP by commenting out  metatag in www/index.html
`<!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;"> -->`
Hope it'll help someone.
