### ISSUE TITLE
App not compatible with my device in Google play store

### ISSUE THREAD

**Issue by philster10260** [phonegap/phonegap-app-developer#176]
Hi,

  I really want to use this app for debugging, but google play will not let me install because it says the app is not compatible with my phone.  I am not too concerned because I am planning to buy a new Android phone for this purpose anyway, but before I buy I must be sure that this app will work on it.

  Can you please reply with the minimum requirements of this app running on Android devices ??

Thank You,
Phil

**Comment by Macwilcy** [comment]
Hi am using Itel 1506 running Android 5.1

Tried installing App through google play and it says "Your device isn't compatible with this version."

I tried installing it on 20/05/2016

Thanks you for your assistance in solving this.

**Comment by RetroCraft** [comment]
I am having a similar issue to @Macwilcy with a Acer Liquid Z380 running Android 5.1.1.

**Comment by surajpindoria** [comment]
Hi @Macwilcy & @RetroCraft,

Please take a look at https://github.com/phonegap/phonegap-app-developer/issues/408.

Unfortunately your device does not meet some minimum standards that we require for our app. You can still manually download the apk and install it yourself and it may work just fine for your needs. But some of the features might not work as intended.

**Comment by Advansoftware** [comment]
acredito eu que essa falta de compatibilidade esta relacionada ao sensor de giroscópio do celular, pois somente esta sendo compatível com celulares que tem essa tecnologia.
