### ISSUE TITLE
No "Done" Button on inAppBrowser

### ISSUE THREAD

**Issue by fboulegue** [phonegap/phonegap-app-developer#181]
Hey i ve got a big Problem with the inAppBrowser
i installed the plugin and added it to the xml file then i added but it still dont work if i put in for example

```
        <a href="#" onclick="window.open('https://groups.google.com/forum/#!forum/phonegap','_blank','location=yes', 'disallowoverscroll=no', 'toolbar=yes');"> IAB without location bar</a> 
```

it still open it as normal link and not in the inappbrowser

**Comment by Anujmoglix** [comment]
Done button /close button is not showing without url. Used "'_blank', 'location=no,disallowoverscroll=no,toolbar=yes'"   and 'location=no, \'disallowoverscroll=no\', \'toolbar=yes\', \'closebuttoncaption=CloseMe\''  all

**Comment by nitin-kapoor** [comment]
Use this customised plugin this will resolve the issue. The customisation is provided for iOS and Android platform.

https://github.com/nitin-kapoor/custom-inAppBrowser-plugin

Below is the command for installing the plugin.
**cordova plugin add custom-inAppBrowser-plugin**
