### ISSUE TITLE
request /__api__/register not working - 404 response

### ISSUE THREAD

**Issue by joanbarros** [phonegap/phonegap-app-developer#187]
I had an issue when the Developer App updated. I used `phonegap serve` to serve the application and used the Developer App to try to run the app and on the phonegap output I got a `404 /__api__/register` everytime I tried to connect, with an "Error!" message on the app.

I got it working by mimicking the api by creating the file `www/__api__/register` with an empty json document:

```
{}
```

After this, I can remove the `__api__` folder completely from my project and it's now working. I've not been able to reproduce the issue just yet, but I'll post more details if I happen to come across it again.

I know for a fact that it's been happening to other people because the only reference to `__api__/register` i can find on Google is for the [Google Play Store page for the app](https://play.google.com/store/apps/details?id=com.adobe.phonegap.app&hl=en) and there's a couple of reviews of people having this issue.

I'm running MacOS 10.9, iOS 7.1.2 and tested with both phonegap 3.4.0-0.19.\* and 3.5.0-0.20.10.

If you need any more detail on this just let me know.

**Comment by sergiaocortes** [comment]
mwbrooks - Thanks.... !!! I have been looking for a solution to this for a while
