### ISSUE TITLE
No platforms added to this project. error

### ISSUE THREAD

**Issue by whitecolor** [phonegap/phonegap-app-developer#203]
I'm trying to run PG app developer on windows (7 x64)

1) I've installed phonegap (npm install phonegap -g)
2) phonegap crate app-name
3) phonegap serve 

I've got an error:
```
...\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova-lib\src\cord
ova\util.js:196
        throw new CordovaError('No platforms added to this project. Please use
              ^
CordovaError: No platforms added to this project. Please use `cordova platform add <platfo
rm>`.
    at Object.preProcessOptions (...\AppData\Roaming\npm\node_modules\phonegap\
node_modules\cordova-lib\src\cordova\util.js:196:15)
...
```

Maybe a wrong repo to post an issue, I've created another in https://github.com/phonegap/phonegap-cli/issues/412

**Comment by john0064** [comment]
mwbrooks. how i can connect to you like: gmail , insta, fb?
