### ISSUE TITLE
App Crashes on IOS when starting

### ISSUE THREAD

**Issue by Josar** [phonegap/phonegap-app-developer#205]
I Installed the Developer App on an old Ipad. but the App crashes at startup.

Following is the Crashdumb First part. Is there any hint to resolv this problem?
>
Hardware Model:      iPad1,1
Process:         PhoneGap [200]
Path:            /var/mobile/Applications/1641EEC6-ED54-4ACF-8EDE-7713C51A5F37/PhoneGap.app/PhoneGap
Identifier:      PhoneGap
Version:         ??? (???)
Code Type:       ARM (Native)
Parent Process:  launchd [1]
>
Date/Time:       2014-09-16 10:34:36.607 +0200
OS Version:      iPhone OS 5.1.1 (9B206)
Report Version:  104
>
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x00000001, 0xe7ffdefe
Crashed Thread:  0
>
Dyld Error Message:
  Symbol not found: _objc_setProperty_nonatomic_copy
  Referenced from: /var/mobile/Applications/1641EEC6-ED54-4ACF-8EDE-7713C51A5F37/PhoneGap.app/PhoneGap
  Expected in: /usr/lib/libobjc.A.dylib
  Dyld Version: 199.6

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
