### ISSUE TITLE
Using cordova.plugins with Phonegap app developer

### ISSUE THREAD

**Issue by vitorsgomes** [phonegap/phonegap-app-developer#209]
Hi,

I'm trying to use File Opener 2 (https://github.com/pwlin/cordova-plugin-file-opener2), when I generate the apk file from cli with cordova build  command everything works like a charm, but if I'm trying to test my app using Phonegap App Developer this error is thrown in my console:

[phonegap] [console.error] Error: undefined is not an object (evaluating 'cordova.plugins.fileOpener2')

Plugins like Camera, File and File Transfer work fine in Phonegap App Developer, it seems to be a bug with some 3rd party plugins.

**Comment by Chener** [comment]
it seems I can not use any plugins, I tried both on Android 4.1 and 4.4。

**Comment by mwbrooks** [comment]
We're greatly improving the build process for the PG Dev App. Once complete, it should allow you to easily add third-party plugins and build your own version.

**Comment by mwbrooks** [comment]
Alright guys, I've [added documentation to the README.md](https://github.com/phonegap/phonegap-app-developer/tree/platforms-as-artifacts#user-content-adding-custom-plugins) to explain how to add a custom plugin and build the app on your local system. At the moment, you must use the `platforms-as-artifacts` branch (this is not mentioned in the README.md). Around next week, you can expect this branch to be merged into `master`.

Cheers!

**Comment by screendriver** [comment]
Thank you @mwbrooks. Unfortunately it does not work. I've added [cordova-plugin-imagepicker](https://www.npmjs.com/package/cordova-plugin-imagepicker)

```sh
$ cordova plugin add cordova-plugin-imagepicker --save
```

after that I did a

```sh
$ npm run -- phonegap run android
```

Now when I make a `phonegap serve` in my project directory my code tells me in my `deviceready` event that `window.imagePicker` is undefined.

**Comment by mwbrooks** [comment]
Hi @screendriver,

Can you try: `$ npm run phonegap -- run android` instead of `$ npm run -- phonegap run android`?

**Comment by screendriver** [comment]
No difference :confused:

**Comment by mwbrooks** [comment]
Hi @screendriver,

Alright,  I've been able to recreate your problem and I've got the plugin working.

The first problem/solution is in Step 3 - Cordova installs an outdated version of the plugin.

The second problem/solution is in Step 6 - the plugin documentation is out-of-date because `window.imagePicker` should be `window.plugins.imagePicker`.

Here are my steps:

1. Navigate to the PhoneGap Developer App repository:

        $ cd phonegap-app-developer/

1. Add the plugin and save it to the `config.xml`:

        $ npm run phonegap -- plugin add cordova-plugin-imagepicker --save
        # or if you have cordova globally installed
        $ cordova plugin add cordova-plugin-imagepicker --save

1. Update the plugin from `1.1.0` to `1.3.0`
  - For some reason, Cordova installs an old version of the plugin
  - Edit the `config.xml` to use the latest version:

          <plugin name="cordova-plugin-imagepicker" spec="~1.3.0" />

1. Compile and run the PhoneGap Developer App:

        $ npm run phonegap -- run ios

1. Create a sample project:

        $ phonegap create my-app

1. Add some image picker code to `www/js/index.js`:

        onDeviceReady: function() {
            app.receivedEvent('deviceready');

            alert(window.plugins.imagePicker.getPictures);

            window.plugins.imagePicker.getPictures(
                function(results) {
                    for (var i = 0; i < results.length; i++) {
                        console.log('Image URI: ' + results[i]);
                    }
                }, function (error) {
                    console.log('Error: ' + error);
                }
            );

1. Serve and connect to the app:

        $ phonegap serve

**Comment by screendriver** [comment]
Oh, ups. So the problem was the plugin itself, not phonegap? I am a bit embarrassed because I've only tried it out with this one plugin to test it with an example app :pensive:

Thank you for your help! :+1: It's working finally! Great! :sunglasses: In our company we waited so long for this feature :wink:

**Comment by mwbrooks** [comment]
It's all good @screendriver! There were a number of problems, so it's natural to assume that it was PhoneGap.

Glad this is a feature that you've been waiting for! Feel free to create issues for any feature that you think would help your company. If we think it can apply to more people, we are open to adding it (Mobile App, Desktop App, or CLI).

**Comment by benjasHu** [comment]
Hi! @mwbrooks I have followed all the steps in your previous comment but *window.cordova.plugins* are still undefined...
In combination with *phonegap serve* must I use it with Phonegap App or simply with the browser?

I have tried both and only been able to work with Phonegap App, but *window.cordova.plugins* is still undefined...

I'm trying to use https://github.com/phonegap/phonegap-plugin-barcodescanner

Any advice about that?

Thanks!

**Comment by screendriver** [comment]
> In combination with phonegap serve must I use it with Phonegap App or simply with the browser?

You have to compile the App by yourself. After that you have to deploy **that** App to your emulator / device. Then you can use `phonegap serve`.

Could you post step by step what you did?

**Comment by benjasHu** [comment]
Ok I understand... but, how could I compile the App? Is the easiest way to compile using Phonegap Build?

**Comment by screendriver** [comment]
> but, how could I compile the App?

It's all documented in the docs: there is section called [adding-custom-plugins](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins).

**Comment by benjasHu** [comment]
I have followed these steps too, but when it is going to finish, console throws this error:

**You may not have the required environment or OS to run this project**

I'm working on a Windows computer and trying to test it on an iPhone... I think this is the problem.

So, Phonegap Build would be my only possible chance? Is there anyway to follow these steps from Windows to test on an iPhone device?

Thanks for your advices :)

**Comment by screendriver** [comment]
Unfortunately not. You **have to** use Mac OS X to develop and deploy an iPhone App :confused:

**Comment by mwbrooks** [comment]
@benjasHu unfortunately, ask @screendriver mentioned you cannot build the iPhone app on Windows.

@screendriver Thanks a lot for following up on this conversation today!

**Comment by screendriver** [comment]
You're welcome :sunglasses:

**Comment by benjasHu** [comment]
Finally I'm using Phonegap Build to test/create my app.
Anyway, thank you both for your support @screendriver @mwbrooks !
