### ISSUE TITLE
How to load plugins?

### ISSUE THREAD

**Issue by screendriver** [phonegap/phonegap-app-developer#220]
I know that the core Cordova plugins are included in the phonegap developer app. But how can I load a custom plugin like com.ionic.keyboard? If it's not possible at the moment: are there any workarounds?

**Comment by Chener** [comment]
@ScreenDriver Hi, how can I use just core cordova plugins like camera ?

 I tried modify `comfig.xml` but the phone just alert api not supported :( 

I also tried to download the core cordova plugins into my app's `plugins/` using `cordova CLI` , still wont work.

Please Help me.

**Comment by ScreenDriver** [comment]
You have nothing to do. All core plugins are working out of the box in the PhoneGap Developer App.

**Comment by timkim** [comment]
Hi @Chener @ScreenDriver 

There actually is a problem with using Camera in the PhoneGap Developer App in that it won't return the image when the camera takes a picture. Please see this issue for more info: https://github.com/phonegap/phonegap-app-developer/issues/174

**Comment by Chener** [comment]
@timkim Well, If I use Phonegap Desktop App to serve, it actully works. See here is the [example](https://github.com/Chener/tlyblOA)
