### ISSUE TITLE
wrong www folder

### ISSUE THREAD

**Issue by mneimne** [phonegap/phonegap-app-developer#223]
OS : Windows 7 64-bit
phonegap version : 3.5.0-0.21.18

create an application on your desktop name it  "test". 
open cmd cd to your application and run phonegap serve, all fine. exit cmd
go to desktop create a folder named www, create index.html and write something in it.
open cmd , cd to the previous application , run phonegap serve . desktop/www/index.html is served.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
