### ISSUE TITLE
camera restart app.

### ISSUE THREAD

**Issue by clembo590** [phonegap/phonegap-app-developer#224]
When calling the navigator.camera.getPicture function, in order to select an image on the device, 
I see all the pictures, but then when I select one, the app restarts (sometimes it restarts sometimes it does not).

I am using phonegap build 3.5 and a motorola G with android 4.4.4.

(I did not see this problem on my iphone).

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
