### ISSUE TITLE
Cookies not working, breaks any app using auth/session cookies

### ISSUE THREAD

**Issue by projekt01** [phonegap/phonegap-app-developer#231]
Cookies are not working. This means a phonegap app using cookies are not working because the application instance is not enable cookies. This breaks any cookie based session concept used by a remote server.

Can you include the cookie manager by default? This could be simply done by change the onCreate method in the PhoneGap app instance. For android this looks::

    # additional import
    import android.webkit.CookieManager;

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        # additional cookie manager config
        CookieManager.setAcceptFileSchemeCookies(true);
        super.onCreate(savedInstanceState);
        super.init();
        // Set by <content src="index.html" /> in config.xml
        super.loadUrl(Config.getStartUrl());
        //super.loadUrl("file:///android_asset/www/index.html")
        com.adobe.mobile.Config.setContext(this.getApplicationContext());
    }

Regards Roger

**Comment by mwbrooks** [comment]
Just following up on this issue. The latest PG Dev App / CLI now uses the `file://` rather than `http://`. I'm going to close this issue, but please let me know if you continue to have a problem!
