### ISSUE TITLE
fullscreen & orientation preferences ignored

### ISSUE THREAD

**Issue by TanaseButcaru** [phonegap/phonegap-app-developer#232]
I'm testing a sample phonegap app on my android device through Phonegap Developer App and I noticed that the fullscreen and orientation preferences are ignored.

Just did a ``cordova run android`` and those preferences works.
I don't know if this is a bug or it's not possible for the app to override its default values for those 2 preferences but I just wanted to let you know.

*Using latest version of cordova/phonegap & android 4.4 on my device.

**Comment by AnotherStar** [comment]
Not fixed yet.....

**Comment by timkim** [comment]
Hi everyone - sorry for the late reply. 

Values in your config.xml will not be read by the PhoneGap Developer App. So things like orientation and fullscreen won't be set unless you build and run the PhoneGap Developer App on your own. 

However, I do believe there is a work around for fullscreen mode for android. We do include the statusbar plugin so I believe it would be possible to simulate fullscreen by turning off the statusbar. Try putting this call to go fullscreen mode ```StatusBar.hide();``` 

From https://github.com/apache/cordova-plugin-statusbar/blob/master/doc/index.md

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Comment by rnlke** [comment]
It would be nice to have the Developer App have a fullscreen option, I tried building a custom version of  the Developer App but couldn't figure it out, maybe the Developer App could include this fullscreen plugin by default? https://github.com/mesmotronic/cordova-plugin-fullscreen
