### ISSUE TITLE
Phonegap serve choose Network Socket

### ISSUE THREAD

**Issue by Josar** [phonegap/phonegap-app-developer#236]
When starting the Serve Programm it will choose a undefined Socket wich is available, maybe first in the list.

The problem is that i have my Laptop connected to the wired Network and to the Wireless network of our Company.  But for testing the App i use Virtual Router Manager as acces point for the Devices to connect and to serve. 

So when i start phoengap serve i have to kill every connection only the Virtual Router with Wifi Miniport Activated to get the program to connect to this specific network. after the server is running activating the connections makes no probelm.

So it would be great to specify or to get a list of networks to choose.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
