### ISSUE TITLE
phonegap serve is not proxying ajax requestes to its host

### ISSUE THREAD

**Issue by whitecolor** [phonegap/phonegap-app-developer#243]
I have development machive with say IP 192.168.1.1

I run phonegap serve on 3000 and my /api server is on the same machine on port 7000.

I have ```<access origin="*" />``` in config file.

I have jquery ajax prefilter that changes IP of ajax requests. And this doesn't work.

```javascirpt
    $.ajaxPrefilter(function( options ) {
        if (options.url.match(/^\/api/)){
            options.url = "http://192.168.1.1:7000/" + options.url ;
        }
    })
```

If I redirect ajax request to some external server
```javascript
            options.url = "http://some-external-server.net/" + options.url ;
```
It everthing works.

**Comment by mwbrooks** [comment]
We no longer require a proxy for external requests. Closing.
