### ISSUE TITLE
3rd party plugins don't work?

### ISSUE THREAD

**Issue by okwei2000** [phonegap/phonegap-app-developer#247]
I include this plugin and the developer app doesn't seems to work
gap:plugin name="wellbload.cordova.background-geolocation" version="0.3.4" 

However, the built application works, so I wonder if the 'app developer' supports 3rd party plugins?

**Comment by timkim** [comment]
With the latest 1.5.2 release, you can now include your own 3rd party plugins by cloning the repo, adding plugins using `cordova plugin add [plugin name]`, and then launching on your device. No need to modify `connect-phonegap`!

**Comment by pharindoko** [comment]
hey timkim - 
so does this mean it`s possible with phonegap developer app to integrate 3rd party plugins like backgroundgeolocation.
I tried to do so by adding the cordova plugin  - cordova plugin add [plugin name]
and executed 'phongap serve' command on server 
but got 'untitled' for $window.plugins.backgroundGeoLocation; when trying to initialize the plugin.

**Comment by iamehiz** [comment]
Plugin is not working after uploading to phonegap build
