### ISSUE TITLE
Send image from camera to another page

### ISSUE THREAD

**Issue by mrodrigolira** [phonegap/phonegap-app-developer#248]
Hello.

I'm having some problems with the camera API. I have two pages, on the first i have a button to open the camera (working), on another i have an <img> element to display the picture taken (not working).

I think the camera is tied to the page that called her, because when i try to display the image on the same page, it works, but when i try to display it on the other page, it doesn't work.

The piece of code that is not working:

       myButton.addEventListener("click", function() {
            navigator.camera.getPicture(onSuccess, onFail, { 
            quality: 50, 
            destinationType: Camera.DestinationType.FILE_URI
            });
        });

        function onSuccess(imageData) {
            window.location = "imagePreview.html";
            document.getElementById("thumbnail").src = imageData;
        }

        function onFail(message) {
            alert('Failed because: ' + message);
        }

**Comment by markjsb** [comment]
I am having similar issue. The developer app isn't allowing access to images. So can't be displayed whether on a separate page or not.

I notice that images are being stored in: file:///storage/emulated/0/Android/data/com.adobe.phonegap.app/cache/image_name.jpg

Don't know if this is an issue.

**Comment by timkim** [comment]
Hi @markjsb and @mrodrigolira 

There is a known issue with camera where you can take a picture but cannot access it from the `file://` uri. This issue is currently tracking this: https://github.com/phonegap/phonegap-app-developer/issues/174

We're currently making a new way to serve the app from `phonegap serve` but will take a little bit to release. We'll let you know when it's ready!

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
