### ISSUE TITLE
Cookie based session doesnt work in the 'App'

### ISSUE THREAD

**Issue by okwei2000** [phonegap/phonegap-app-developer#253]
The sessions of an ajax call and static http request (e.g. img src="http://samedomain.com/theImage.jpg") are different. However, when it's built in phonegap, it's working fine.

**Comment by rlaurente** [comment]
Hi @mwbrooks I see the proxy thing works. but in my app now, I'm using passport to login with socialnetworks(fb, ig, twitter and etc). and I tried adding "/proxy/" before the url but it's throwing broken urls, specially when it's going to redirect to social network login. do you have idea, how to implement proxy with passport js ?

thanks

**Comment by mwbrooks** [comment]
Hi @rlaurente,

The latest PG Dev App / CLI now renders apps from the `file:///` rather than `http://`. This should allow you to access external services without the proxy workaround. 

Let me know if you continue to have issues!

**Comment by mwbrooks** [comment]
I'm going to close this issue. Please let me know if you have any issues.
