### ISSUE TITLE
one ip address works, one times out

### ISSUE THREAD

**Issue by jegarne** [phonegap/phonegap-app-developer#261]
When I start the phonegap server it appears to alternate between two IP addresses: 10.13.245.79:3000 and 10.13.58.116:3000.  When I enter these into the phonegap developer app, the first one works successfully.  With the second one, the app tries to open but returns to the start screen and when I submit the second time it returns error - time out.

What this means in practice is that I have to restart the server until I get the working IP address.  Note that I'm trying both addresses on the same network, and both my pc and device (iOS) were not disconnected from the network after I started the server.

**Comment by mwbrooks** [comment]
Hi @jegarne,

This is an interesting issue that I've never experienced. It looks as though your network subnet mask is configured differently than most networks that I've used.

The next time that this happens, can you enter the server address into your device's browser? If the browser connects to the server, you'll see your app but deviceready will not fire. I'm simply curious whether a default browser can reach the server - if it can't, we may see a meaningful error message.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
