### ISSUE TITLE
Unresponsive page after accessing camera

### ISSUE THREAD

**Issue by markjsb** [phonegap/phonegap-app-developer#265]
After accessing the camera the page is unresponsive to tap events, even trying to fire the camera again.

**Comment by mwbrooks** [comment]
@markjsb Thanks for submitting an issue!

Could you provide us with:
- Platform and version (e.g. Android 4.3)
- Device model
- A code snippet of the camera API that you're invoking

Thanks!

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
