### ISSUE TITLE
Enabled Orientation

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#266]
Is it just me or has landscape mode become disabled? On our first launch, only portrait-mode was enabled. However, #107 added landscape mode support for iOS. I'm now testing on my iOS device and I can only produce portrait mode.

**Comment by timkim** [comment]
Oh ya that makes sense that you can't go landscape anymore. I'm pretty sure the last upgrade (to cordova 4.0.0) didn't include that ios change since it changed the plist file directly.

**Comment by mwbrooks** [comment]
Alright, we should resolve this for the next release. We should also create a hook that can auto-add the plist settings, so that we can continue moving towards platforms as an artifact.

**Comment by lucasdamiani** [comment]
Do you know when the release with this fix will be available?

**Comment by TianleZhang** [comment]
Same question from here

**Comment by timkim** [comment]
Hi @lucasdamiani and @TianleZhang 

I'll see if I can gear up for an app release this week. I'll keep you posted!

**Comment by ewagnerdesign** [comment]
Having this same issue.  Orientation is locked in portrait and will not go to landscape on Phonegap Developer app or Ionic View app.  On the iOS emulator, the orientation changes correctly.  When can we expect a fix?

**Comment by caseypt** [comment]
+1

**Comment by timkim** [comment]
Should be in now as of this commit: https://github.com/phonegap/phonegap-app-developer/commit/b23e27550f147f18a888ee58b17423d0b0584eb8

The app itself is in the review stage in the apple store so it should be available to the public in about a weeks time. Sorry for the delay!

**Comment by jackanderson** [comment]
I am still having this issue on the ios version of the phonegap developer app. Setting landscape mode does nothing. It works properly in the ios emulator.

**Comment by asapp-kv** [comment]
I'm also having this issue with the latest iOS version of the PhoneGap Developer app (1.5.4) and PhoneGap (5.2.0).

**Comment by brunocasanova** [comment]
i'm having this issue too with the latest IOS version and PhoneGap developer. Just can't get anyway to make it in landscape.

**Comment by matr1xprogrammer** [comment]
I am also having the same issue. Using PhoneGap (5.2.3) iOS (8.4). Could you please advise? Thanks.

**Comment by dooderlani** [comment]
It's November - I am having this issue too - and no one has commented on this in months...

**Comment by mwbrooks** [comment]
Hi @dooderlani,

The latest release to iOS and Android support landscape and portrait orientation. Windows Phone is locked in portrait.

- What platform are you using?
- Are you using the latest App Store release?

**Comment by dooderlani** [comment]
Hi @mwbrooks thanks for your super fast reply

I am testing both android (4.2.2 - jellybean) and iphone (5 - 8.4). I downloaded the PhoneGap developer app this weekend.

In the widget tags I added this to the root config file:
<platform name="android">
        <allow-intent href="market:*" />
        <preference name="orientation" value="landscape" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="orientation" value="landscape" />
    </platform>

I also added orientation specs to the android/AndroidManifest.xml

**Comment by mwbrooks** [comment]
Hi @dooderlani,

Ahhhhh! Currently, the PhoneGap Developer app turns on landscape and portrait for all apps, regardless of the app's local configuration (config.xml). The preview never uses the local configuration. We want to add this feature, but it wasn't high on our priority list (connecting, updating, and render the app accurately has been our top priority).

However, I think it's time that we add this feature. I've created issue #373 to track this progress. Feel free to +1 it or even send a pull request implementing the feature!

**Comment by dooderlani** [comment]
ok - thanks for the 411 @mwbrooks. The desktop and phone app partnership is pretty fantasmic. I am plusin' it now
