### ISSUE TITLE
navigator.contacts.pickContact is undefined

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-app-developer#268]
`navigator.contacts.pickContact` is undefined when previewing in the PhoneGap Developer App.

Related to: https://github.com/phonegap/phonegap-app-desktop/issues/278

**Comment by timkim** [comment]
Just tested on both android and ios. I can confirm that the `navigator.contacts.pickContact` is undefined from a served app. However, if you try calling `navigator.contacts.pickContact` from the `phonegap-app-developer` (ie, somewhere like here https://github.com/phonegap/phonegap-app-developer/blob/master/www/js/app.js) it will return a function. Seems like `navigator.contacts.pickContact` is unavailable through a served app. Not sure why but will have to investigate further.

**Comment by timkim** [comment]
On further investigation I've found that `connect-phonegap` is serving the incorrect `contact.js` file it seems. The `pickContact()` is clearly in the plugins in the `phonegap-app-developer` (https://github.com/phonegap/phonegap-app-developer/blob/master/plugins/org.apache.cordova.contacts/www/contacts.js#L66) but is absent in the corresponding app version in `connect-phonegap`: https://github.com/phonegap/connect-phonegap/blob/master/res/middleware/cordova/3.6.4/android/plugins/org.apache.cordova.contacts/www/contacts.js and https://github.com/phonegap/connect-phonegap/blob/master/res/middleware/cordova/3.6.3/ios/plugins/org.apache.cordova.contacts/www/contacts.js. Will need to update `connect-phonegap` and that ought to do the trick.

**Comment by timkim** [comment]
Ok, the fix should be in `connect-phonegap` on version `0.14.7`.
