### ISSUE TITLE
The use of phonegap WebView JS injection in the Android 4.3 system version, return the results of delays, that is to use JS loadurl method to load caused by thread occlusion, how to solve?

### ISSUE THREAD

**Issue by gaobin881201** [phonegap/phonegap-app-developer#269]
This is my code
public void onPageFinished(WebView view, String arg1) {
				// TODO Auto-generated method stub
			
				setTitle(cordovaWebView.getTitle());
				if (!TextUtils.isEmpty(jsStr)) {
					final StringBuilder js = new StringBuilder();
					js.append(
							"var newscript = document.createElement(\"script\");")
							.append(jsStr)
							.append("document.body.appendChild(newscript);");
					if (android.os.Build.VERSION.SDK_INT < 19) {

						cordovaWebView.loadUrl("javascript:" + js.toString());
					} else {
						cordovaWebView.evaluateJavascript(
								"javascript:" + js.toString(), null);
					}

				}
			}
Android 4.4 using evaluateJavascript does not appear to delay.

**Comment by mwbrooks** [comment]
Hello @gaobin881201,

I'm sorry to hear that you've run into an issue with Android 4.3. However, this appears to be something specific to Cordova Android and not the PhoneGap Developer App (this issue tracker).

Can you please file an issue in the [Apache Cordova Issue Tracker](https://issues.apache.org/jira/browse/CB) with the _Android_ component.

Good luck!
Michael
