### ISSUE TITLE
Define network interface phonegap serve

### ISSUE THREAD

**Issue by koxder** [phonegap/phonegap-app-developer#275]
I have a vagrant machine for phonegap developing. I am facing troubleshooting when i launch
phonegap serve because is served on first interface but on Vagrant machine you should have adapter 1 as nat interface (for vagrant configuration). So my question is : 

Can i define what interface I interested on use as server? Something like that:

phonegap serve eth1

**Comment by mwbrooks** [comment]
Hi @koxder,

The IP address output by the PhoneGap serve command is simply the tools
best guess at your machine's IP address. Have you tried connecting to your
Vagrant system's IP address and port that you've configured in the
Vagrantfile? It may still connect even if the PhoneGap server command is
outputting a different IP address.

If that doesn't solve your issue, we can look into adding the ability for
your to specify the network interface that is binded to the server.

Cheers,
Michael

**Comment by koxder** [comment]
Before all, thanks for your quick response.

Yes, you are right. Trying to Vagrant system's IP address I can connect. 

Thank you very much

**Comment by mwbrooks** [comment]
Awesome. We should find a way to list all available IP address (when needed). Perhaps hiding it behind a flag?

**Comment by koxder** [comment]
Yes, would be a great idea. 
Although printing that app is available on all interfaces would be enought at least for me.

Thanks again.
