### ISSUE TITLE
Debug with chrome and phonegap app developer

### ISSUE THREAD

**Issue by koxder** [phonegap/phonegap-app-developer#276]
Hi,

I develop a demo app, I use phonegap app dev to deploy my app on all mobiles wich I use to test. But my problem is when i trying to debug with google chrome because my app is not listed on:

chrome:inspect

If i install  my app on my mobile I can debug from chrome:inspect. Maybe I have to add some extra config to remote debug with chrome.

Thanks.

**Comment by mwbrooks** [comment]
Hi @koxder,

This is a feature that we really want to add, but it is currently unsupported. We're currently tracking the feature in #49 Enable Remote Web Inspector in Production. When an application is compiled in debug-mode, it is possible to discover and connect to the app's browser using remote web inspector (for example, with `chrome:inspect`). However, once compile as a production release, the remote web inspector is disabled.

We've planning to tackle this in April after the Content Sync feature is shipped to solve the CORS issues related to external domain XHRs and accessing the file system.

If you happen to have any insight that could help us speed up adding the Remote Web Inspector feature, we'd greatly appreciate some comments on #49! I'm going to go ahead and close this issue, but feel free to continue leaving some comments!
