### ISSUE TITLE
PhoneGap Developer error "TIMED OUT"

### ISSUE THREAD

**Issue by mario9981** [phonegap/phonegap-app-developer#278]
Hi, i'm new with PhoneGap.

first connect to server from my laptop
phonegap serve 
starting app server..
listening on 192.168.1.74:3000

when i try to connect from my Android device samsung note 10.1 2014
with 192.168.1.74:3000 address,  i received error message "ERROR"-"TIMED OUT"

How can i fix that?

Than you for advance!

**Comment by timkim** [comment]
Hi @mario9981 

Do you see anything else being logged in the terminal when you try connecting? Or does it just hang on `listening on 192.168.1.74:3000`?

**Comment by mario9981** [comment]
[phonegap] starting app server...
[phonegap] listening on 192.168.1.75:3000
[phonegap]
[phonegap] ctrl-c to stop the server

**Comment by timkim** [comment]
Hi @mario9981 

Are you sure you have your device and your computer on the same network? See if you can `ping` your device's ip.

**Comment by mario9981** [comment]
Hi Tim,

Yes i can ping my device ip, through my pc.

Before a month i downloaded phonegap developer app in my device and
phonegap app version 0.1.1 on my pc and i could connected.  Next day when i
tried to connect, i couldnt. Now i have the latest version on my pc but i
still cant connect (timed out)
 Στις 23 Μαρ 2015 8:25 ΜΜ, ο χρήστης "Tim Kim" <notifications@github.com>
έγραψε:

**Comment by timkim** [comment]
Hi @mario9981 

Sorry for the long delay - we've been trying to figure out a collection of issues and we're finally making some progress here. However for your problem, I'm still unsure what exactly is the issue. Do you mind taking some time filling out this questionnaire for us? https://github.com/phonegap/phonegap-app-developer/issues/307

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
