### ISSUE TITLE
IP chosen by phonegap serve is not on local network

### ISSUE THREAD

**Issue by MaelstromCdn** [phonegap/phonegap-app-developer#279]
Hi there,

I am trying to test a new app on Windows. When I run "phonegap server" to test my app, it comes up as IP 169.254.80.80:3000 where my local network is 192.168.0.x. This is preventing me from connecting to the server from my device. My subnet masks appear to be the default 255.255.255.0. I actually had this working fine on another computer on the same network the other day.

I installed the tools this morning base on the instructions here: http://app.phonegap.com/. In case it matters, I've also previously installed the Cordova tools for Visual Studio on this machine.

Thanks,
Jason

**Comment by Xalas11** [comment]
I had the same problem, i think it could depend on the installed network adapters. The virtualnetwork adapter of the windowsphone emulator for example uses the IPv4-Adresse: 169.254.80.80. To deaktivate all Internet adapters except the i use worked for me like a charm.

maybe it helps
greets

**Comment by MaelstromCdn** [comment]
Thanks Xalas11, that put me on the right track. It was the windows phone emulator adapter messing me up too. You can disable or I discovered you can just set your primary adapter to a higher priority using the instructions from here: http://www.eightforums.com/tutorials/20148-network-connection-priority-change-windows.html
