### ISSUE TITLE
cordova.js missing by default?

### ISSUE THREAD

**Issue by aliakhtar** [phonegap/phonegap-app-developer#281]
If I run the 'hello world' app, via:

`phonegap create test`
`cd test`
`phonegap serve`

Then, the `deviceready` event is never fired, and the app remains stuck on the 'connecting' screen. I believe this is because there is no `cordova.js` file present in `www`.

If I manually copy `cordova.js` from `platforms/android/www/` to `www`, then `deviceready` is fired up without any issues.

Is this expected, or am I missing something?

**Comment by timkim** [comment]
Hrm - when you use `phonegap serve` it should serve all of the `cordova` assets (ie, `corodva.js', `plugins/` and 'cordova_plugins.js`) to the developer app. Can you provide what the output looks like on the terminal after you connect with your phone?

**Comment by Denouncer** [comment]
I'm having the same issue. My app hasn't changed and worked perfectly before the recent update. Now it doesn't fire deviceready anymore. I have "<script type="text/javascript" src="phonegap.js"></script>" at the top of the script, but it seems this file is no longer being created. Frustrating :(

**Comment by timkim** [comment]
Hi @Denouncer 

Try including `cordova.js` instead of `phonegap.js`:
` <script type="text/javascript" src="cordova.js"></script>`

**Comment by Denouncer** [comment]
@timkim thanks. that did it. :P

**Comment by mwbrooks** [comment]
Nice!
