### ISSUE TITLE
net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by itree** [phonegap/phonegap-app-developer#284]
Hi, 
I compiled the app from the code cloned from the master.  It is installed on android, but when I try to connect to an app. It gives me the error:

net::ERR_FILE_NOT_FOUND (file:///data/data/com.adobe.phonegap.app/files/fils/phonggapdevapp/www/inded.html)

I compiled exactly as how it is specified in the instructions.

**Comment by dfrancesch** [comment]
It happened to me too.
The path in itree's message has some mistakes...
the rigth path is: file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/index.html

Thanks in advance.
Daniel.

**Comment by itree** [comment]
Thanks.  For typing the correct path.

**Comment by dfrancesch** [comment]
I cloned the release tagged "1.4.0-android-release" and it works for me now.

**Comment by timkim** [comment]
Hi @itree 

We've recently switched over to a new way of serving content to the `phonegap-app-developer`. What you're seeing is an error message from using an older version `connect-phonegap` trying to connect to the new `phonegap-app-developer`. If you use `connect-phonegap@0.16.0` or `phonegap-cli@5.0.0-0.28.0` - that should fix your problems.

**Comment by itree** [comment]
Ok I see.  Thanks.
