### ISSUE TITLE
it's iOS PhoneGap Developer a little bit outdate?

### ISSUE THREAD

**Issue by wozzup** [phonegap/phonegap-app-developer#285]
cordova and all plugin is updated: http://cordova.apache.org/news/2015/04/21/tools-release.html to a major version, but seem iOS PhoneGap Developer still in 2014-11-27?

**Comment by timkim** [comment]
Hi @wozzup 

Ya, we're still on the `cordova@4.0.0` versions of the plugins. We were busy fixing some things internally and didn't want to upgrade just yet but we just finished :). We'll be updating to the new `cordova` soon.
