### ISSUE TITLE
Phonegap project put onto latest Android studio doesn't work.

### ISSUE THREAD

**Issue by alexwastaken** [phonegap/phonegap-app-developer#286]
Hi,

I am trying to develop an application with Phonegap and I wanted to know if there is anyway that I can import my project successfully onto the sdk. I have tried importing the project folder, the zip file, and even converting the file into an apk and I get the same error, "no frameworks detected". If anyone is using the Android studio to develop their Phonegap app please help!

Thanks!

**Comment by mwbrooks** [comment]
Closing because we are focused on CLI-based development. Sorry!
