### ISSUE TITLE
App not connecting on PC to Android

### ISSUE THREAD

**Issue by schreyers** [phonegap/phonegap-app-developer#290]
Since the update, I can't connect my Samsung 4S running the phonegap app to connect to CLI or Desktop app serve. Was working yesterday (26th May 2015).

I have Windows 7 64bit Phone is running Android version 4.4.2

Cheers!

**Comment by mwbrooks** [comment]
Hi @schreyers,

Can you please update the PhoneGap CLI to the latest version using:

```
npm install -g phonegap
```

I'm going to close this issue. If the above suggestion doesn't solve your issue, feel free to reopen it or leave a comment and I'll reopen it.

**Comment by schreyers** [comment]
Cheers Michael, 

Should of said that i'd done that sorry. I'm running phonegap version 5.0.0-0.28.1. I have also removed and re-installed the phonegap app to be sure.

I have tried having the files on a memory stick (previously working) or on the desktop but i still just get the downloading... then timeout error on the app.

I've tried doing through the phonegap desktop app but still get the same issue.

**Comment by mwbrooks** [comment]
@schreyers Ah, cool. Well, we're looking into this issue but it's been difficult to recreate. I've tested on an Android 4.4.2 (Galaxy Nexus) and it worked okay on my end. The only difference is that I used OS X and Windows 8.

I'm curious whether it could be a network issue. Are you using a large or high volume network (corporate or overloaded coffee shop)? I've tested on a hotspot, home network, and sketchy coffee shop network without any problems.

**Comment by schreyers** [comment]
Cheers Michael, 

It wouldn't be a network thing as I run my PCs internet through my phone. Its a home network as well so only a few devices on it.

I've tested it all again and its still not working.

Is there a way of getting an older version of the app? I have the old version on my iPad but you can't connect from PC iPad unless there is a knack to it?

Appreciate the effort so far!

**Comment by schreyers** [comment]
Hi Michael, 

I did some more testing last night which might be useful.

I tried downloading phonegap app on a Samsung S5 instead to see if it was android version software causing it but still got the same issue of 'Downloading...' then timeout.

I also tried getting the IP address wrong on purpose to see if i got a connection error immediately but still got the 'Downloading...' for the same amount of time before the timeout message. Not sure if that helps at all.

Thanks again!

**Comment by schreyers** [comment]
@mwbrooks I have made some progress in finding the issue. I needed to re-install node.js. I then re-installed phonegap as well and now it connects. 

Not sure why this was a cause. I had a random issue a while back where i installed sass at home and that broke phonegap till i re-installed node.js. Just tried it again as a long shot and bingo!

Thanks

**Comment by mwbrooks** [comment]
Hey @schreyers, whoa, that's a really odd issue. I've got a few more Windows 7 users with connection issues, so maybe I'll pass on your suggestion.

Thanks for the update and I'm glad to hear that you're back in business!
