### ISSUE TITLE
Freeze after Success!

### ISSUE THREAD

**Issue by Adtiv** [phonegap/phonegap-app-developer#292]
I am using iphone 5, updated latest phonegap cli 5.0.0-0.28.0, and latest app update 1.5.2. Since the 1.5.2 update i cannot connect to my app. It gets all the way to Success! and then freezes. I am running windows 7 and in the command line it gets to [phonegap] 200/__api__/appzip and nothing further. Any suggestions?

**Comment by mwbrooks** [comment]
Hi @Adtiv,

Truthfully, I've only tested on Windows 8. Would you mind trying something out for me?

1. Run `phonegap serve`
2. Open your desktop web browser to http://x.x.x.x:3000/__api__/appzip
  - Replace `x.x.x.x` with your IP address
3. It should download a zip archive
4. Unzip the archive
5. Verify that it is your app (just glance at the files; nothing too detailed)

Thanks!

**Comment by Adtiv** [comment]
Looks okay, got a zip file of my app/files

**Comment by mwbrooks** [comment]
@Adtiv great, in that case I think it's safe to say that Windows 7 is not the issue.

Next, we will want to checkout the iPhone 5. I'll track down a spare device to test on.

**Comment by Adtiv** [comment]
Any luck? Just updated my phone from ios7 to ios8 and still running into the same problem

**Comment by mwbrooks** [comment]
Hi @Adtiv,

My iPhone 5 (non-S) connects correctly on OS X and Windows 8.1 (x64).

Two ideas that have came to mind while I've been testing are:
1. Any chance that you app is large? Say, above 20MB?
2. Any chance that your Windows computer has multiple IP Addresses? Sometimes, the PG Desktop/CLI displays the wrong IP Address because Windows has multiple IP Addresses. In your Command-Prompt you can list your IP Addresses using `ipconfig` (they are listed as _IPv4 Address_). If possible, can you try the other addresses listed to see if any of those connect.

**Comment by Adtiv** [comment]
The app folder is around 45mb but most of the space is taken up by my "platforms". Also i only have one IPv4 address which is the one that i have been using.

**Comment by Adtiv** [comment]
I've tried two different iphone 5's an iphone 4 and an ipad and got the same error(freeze at success!) for all of them. It worked on a windows phone tho when i used the same phonegap serve address i was using for the iphones. Also, one of my team mates who has windows vista(i have 7), updated version of phonegap, and the updated code got it to work with her iphone5 on her computer. I'm at a complete loss as to why this is happening, but it seems that newest phonegap update + ios + something to do with my specific network/computer? is causing the error. You have any idea of anything else i can test? Would really love to get this up and running again.

**Comment by mwbrooks** [comment]
@Adtiv thanks a bunch for continuing to test this out! The more information that I can gather, the quicker we can resolve this problem. I've actually started [compiling a list of reported issues](https://coggle.it/diagram/VXCPQhPIr38Gm9fg) to better understand the relationship of operating systems and devices.

That's very interesting about your teammate. A few questions that come to mind are:

- She is on the same network as you?
- Was she testing the same app as you or the smaller Hello World app?

Cheers,
Michael

**Comment by Adtiv** [comment]
No problem, thanks for helping out! She was on a different network as me testing the same app. The windows phone that i tested on and all of the ios devices were on my network/computer(the windows phone worked). Also something interesting, just dl the Hello World phonegap project from github and it worked on my iphone 5!

So something with the update caused my specific project to not work on ios devices using my network/computer, but still work for my team mate on her network/computer? Atleast i know now that I'm getting the correct ip address and my phone can still connect to pg projects.
-still confused on why our project would work for my team mate on a different computer.

**Comment by Adtiv** [comment]
Another thing, after trying out the hello world project, it got "stuck" in the server. Exiting the command prompt and the developers app, restarting both and navigating to my own app project folder(in a completely different location than hello world project) and doing phonegap serve, brings up the hello world project. It continually brought up the hello world project after restarting the command prompt/app many times and being in my own project directory. This even kept happening after restarting my computer and deleting the hello world app from my computer. I resolved it by restarting my phone, in which i got the standard timeout error on my project. Then after restoring the deleted hello world project and trying that, i was able to connect, but then it got "stuck" again and i had the same problem as above.

**Comment by Adtiv** [comment]
Found the problem.. my index.html was spelled with a capital "I". my xml content source was with a lowercase. Not sure why it bugged out like this on ios and continued to work on Android/windows phones i tested on and also on my team mates iphone5(also looked through my commits to see if i accidentally changed the file name after the update and i didn't). Anyways, after renaming my index.html to have lowercase it worked! hours spent on this stupid thing...    

Well now I'm able to access my app, but changes dont show up until I restart the developers app :/

**Comment by timkim** [comment]
Hi @Adtiv 

Oooo, the capital "I" typos are the worst. Well, glad to hear you got it working. We also just released an update for the app that should fix the reload issue.

**Comment by ronnievdc** [comment]
I got the same Bug, but other problem.
My www folder was a symlink to www_v3 (i had also www_v2 of www_v1). The zip ended up with www_v3 as rootfolder instead of www.
After removing the symlink and rename www_v3 to www solved the problem.

I'm using Ubuntu 14.04
Phonegap: 5.0.0-0.28.1

**Comment by surajpindoria** [comment]
Closing this, issue has been resolved.
