### ISSUE TITLE
Developer App and Desktop App compatibility issue

### ISSUE THREAD

**Issue by piyushgupta123** [phonegap/phonegap-app-developer#294]
I have upgraded my PhoneGap Developer App, and its showing Download Error "Update Command Line". I have 32 bit OS installed, and new version of Desktop Apps work only on 64 bit. What should I do now?? Neither older version of Developer App is available nor I can work with older Desktop App.

**Comment by iamehis** [comment]
same here is not connecting here

**Comment by mwbrooks** [comment]
@piyushgupta123 Sorry for the trouble. We are in the process of releasing a 32-bit version of the Desktop app: phonegap-app-desktop#365

@iamehis Have you updated the PhoneGap CLI or Desktop app to the latest version? If so, we're seeing the same issue on a few user devices. Keep an eye on the other issues to get a sense of our progress. It would be helpful if you can leave the PhoneGap CLI version (`phonegap --version`) or Desktop app version (File -> About). Also your device, platform, and operating system version. Thanks!
