### ISSUE TITLE
Update timeout message to not mention CLI

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#296]
At the moment, the timeout message asks the user to check their connection and update their CLI. However, many of our users are now using the Desktop app. As a result, this error message is inaccurate and misleading.

**Comment by timkim** [comment]
Fixed in this commit: https://github.com/phonegap/phonegap-app-developer/commit/b88b9e9acb36ced606cbd69dde9af116f31bfae9
