### ISSUE TITLE
phonegap doesnot install on windows 8

### ISSUE THREAD

**Issue by Malli585** [phonegap/phonegap-app-developer#297]
phonegap doesnot install on windows 8. it shows the error like 'network tunneling could not be established' on cmd.
please help me to install phonegap.
my operating system is windows 8. and i already installed nodejs software. but no use.
thank you
![phoneg](https://cloud.githubusercontent.com/assets/12757773/7999992/29983b94-0b72-11e5-85fb-8d46edaceeed.JPG)

**Comment by mwbrooks** [comment]
Hi @Malli585, it sounds like this issue is related to the npm proxy settings. Would you mind reading through [this issue on 'tunneling socket could not be established'](https://github.com/npm/npm/issues/2472) to see if you can find a resolution.

**Comment by surajpindoria** [comment]
Closing this issue, I do not believe it is a problem with PhoneGap but instead with npm settings. The above link has solutions, [here](http://stackoverflow.com/questions/32783561/npm-wont-install-packages-npm-err-network-tunneling-socket-could-not-be-estab) is a more concise version.
