### ISSUE TITLE
Unable to download archive from server. Please update PhoneGap CLI issue.

### ISSUE THREAD

**Issue by anshumittal2208** [phonegap/phonegap-app-developer#305]
Hi,
I have downloaded phone gap desktop version 0.1.7 on my windows 8.1 enterprise.
I have android device of version 4.2.1 
I have downloaded phone gap developer of version 1.5.2
I m not able to connect my phone app with desktop app
Please help.

**Comment by timkim** [comment]
Hey there @anshumittal2208 

It seems like things should be working on your end - would you mind filling out this [questionnaire](https://github.com/phonegap/phonegap-app-developer/issues/307) to help us trouble shoot this connection issue? You might also figure out where the error is in your setup from that questionnaire.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Comment by rimagahwa** [comment]
I'm having the same problem

**Comment by AnilGupte** [comment]
I solved the issue by unblocking port 3000 in Windows Firewall  See https://msdn.microsoft.com/en-us/library/ms175043.aspx for how to do it.
