### ISSUE TITLE
Phonegap Orientation Issue

### ISSUE THREAD

**Issue by Pristo** [phonegap/phonegap-app-developer#311]
Orientation in app is forced to portrait, can't change it...
![img_0003](https://cloud.githubusercontent.com/assets/1492794/8305033/25810d30-19a3-11e5-8b55-49da899c81d4.PNG)

Ipad 2 (MC979B/A)
iOS 8.3
App version 1.5.4

**Comment by bartwitt** [comment]
I have the same problem, been there since a week. Probably introduced in this last 1.5.4 version.

**Comment by mdjimy** [comment]
I have the same problem too

**Comment by timkim** [comment]
Hey all, 

Thanks for pointing this error out - the fix should be in the next release.

**Comment by jw8** [comment]
+1

**Comment by n4ru** [comment]
Still not fixed. A little ridiculous given that this issue has been reported for at least [15 months](https://github.com/phonegap/phonegap-app-developer/issues/117)

**Comment by jackanderson** [comment]
+1

**Comment by dazlious** [comment]
+1

**Comment by mwbrooks** [comment]
I believe this has been fixed in the latest app store release. Works on my iPhone 6.
