### ISSUE TITLE
Add Icons and Splash Screens to config.xml

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#313]
Once the platforms are set as artifacts, we will need to declare the icons and splash screens in the `config.xml`

**Comment by timkim** [comment]
It appears that there is no documentation on how to copy over the default icon image size to the `platforms/android/res/drawable/` on android. There's probably some way to do it, but I'll have to dig into the cli logic to figure it out. 

As you can see from the docs: http://docs.phonegap.com/en/edge/config_ref_images.md.html#Icons%20and%20Splash%20Screens

Only the icons that are attributed to some density are listed and not the default one. Pretty annoying :(

**Comment by timkim** [comment]
Well after some investigation it appears that needing the default `drawable` folder isn't necessary: 
https://issues.apache.org/jira/browse/CB-8897

**Comment by mwbrooks** [comment]
Added iOS Splash Screens and tested on simulators.
