### ISSUE TITLE
Add iOS 8 Support

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#316]
I'm unsure why this has taken so long, but we should add iOS 8 support to prevent pixated displays. This may be solved simply by treating the iOS native project as an artifact. If it is a more involved solution, we can break it out to separate milestone.

**Comment by blefebvre** [comment]
As a workaround, I was able to jury–rig iOS 8 support for a demo by removing the iOS platform and re-adding it with PhoneGap CLI v5.1.1:
```
$ phonegap platform rm ios
$ phonegap platform add ios
```
The app icon and splashscreen were the Cordova defaults, but other than that it seemed to work fine. I did not run the tests or try out any core plugin functionality.

**Comment by mwbrooks** [comment]
Great, thanks @blefebvre. Since the latest milestone is treating the platforms and plugins as build artifacts, each build will re-add the iOS platform. So we should see iOS 8 support properly work now.
