### ISSUE TITLE
Add Continuous Build Support to WP

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#320]
Build WP on each commit to `master`.

**Comment by timkim** [comment]
The windows' ad hoc release process is kinda annoying. See listed process:

1. The company registers a company developer account and acquires an enterprise certificate from Symantec.
2. The company creates an application enrollment token (AET).
3. The company develops a Company Hub app.
4. The company prepares their apps for distribution.
5. Employees (or other users) enroll for company app distribution on their phones and install the company apps by using the Company Hub app.

Right now, @mwbrooks is talking to someone within adobe to get the Symantec enterprise cert and should be available for use soon.

**Comment by timkim** [comment]
Thanks to the pg build team and their certs we can now sign an ad hoc app for hockey app.
