### ISSUE TITLE
Implement Content Streaming on WP

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#324]
The plugin should intercept all external HTTP requests matching a certain server end-point, cache the content locally, and rewrite the response to have the browser load the content locally.

No idea whether this is even possible.

**Comment by darkyen** [comment]
I'd like to help on this, where do i start ?

**Comment by mwbrooks** [comment]
Closing this issue. Right now, we don't plan to look into this approach.

@darkyen thanks for the offer! However, for now we are going to stick with the zip deployment approach. If you're interested in helping out in other ways, feel free to reach out!
