### ISSUE TITLE
Accessibility of PhoneGap app's WebView

### ISSUE THREAD

**Issue by ajgarrison** [phonegap/phonegap-app-developer#327]
Hi, 

I was not able to debug the Webview through Chrome / USB / Mobile - has debugging been enabled?

https://developer.chrome.com/devtools/docs/remote-debugging#debugging-webviews

Very best regards

Alistair

**Comment by timkim** [comment]
Hi @ajgarrison 

You won't be able to remote debug your app if you are running the `phonegap developer app` downloaded from the app store. To debug the app like you would in the article you linked, you have to build, compile and launch the app on your own machine.
