### ISSUE TITLE
Autoreload does not send a new project app to be downloaded when switching between projects

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-app-developer#334]
Scenario:
1) `cd` into existing phonegap project
2) `phonegap serve`
3) connect on device 
4) `ctrl + c` to kill the server
5) `cd` into another phonegap project
6) `phonegap serve` 
7) connected device will hit the `autoreload` end point, but not update to the new phonegap project being served

We will need a way to detect when we change between projects and handle that gracefully.

**Comment by aaronagray** [comment]
Does anyone have an update on this or know a quick workaround? I just started my second PhoneGap project and am experiencing this for the first time.

**Comment by aaronagray** [comment]
Restarting my computer and the developer app worked for me.

**Comment by surajpindoria** [comment]
Fixed in https://github.com/phonegap/connect-phonegap/commit/df13d7c6ea7bea39426ca4e42c1c8e2fb0fc5d73. Waiting till after PGD to release

**Comment by aaronagray** [comment]
Awesome! Thanks!

**Comment by surajpindoria** [comment]
Merged in to the latest CLI.

@aaronagray if you update your CLI you should be able to see this functionality.
`npm install -g phonegap`
