### ISSUE TITLE
Set the status bar style to show black text/icons rather than white on iOS

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-app-developer#337]
The [Status Bar plugin](https://github.com/apache/cordova-plugin-statusbar) automatically adds some preferences to the [platform-level config.xml for iOS](https://github.com/phonegap/phonegap-app-developer/blob/master/platforms/ios/PhoneGap/config.xml), which defaults to white text/icons unless you specifically override it in the root config.xml or in the code. This line is what is automatically added to specify the status bar style: 
    
```<preference name="StatusBarStyle" value="lightcontent" />```

Black font/icons would look better for the wrapper app since it's using light colors. To fix it, we can just add the following preference to the [root project config.xml](https://github.com/phonegap/phonegap-app-developer/blob/master/www/config.xml) to override the platform-level one:

   ``` <preference name="StatusBarStyle" value="default" />```

(Note: the line in config.xml specifiying```<preference name="ios-statusbarstyle" value="black-opaque" />``` is only relevant for PhoneGap Build.)

**Comment by mwbrooks** [comment]
Let's review how the `default` value looks on Android and WP8.

@surajpindoria can you post a screenshot of each platform, so we have an idea of how it looks?

**Comment by surajpindoria** [comment]
![ios simulator screen shot sep 14 2015 12 02 54 pm](https://cloud.githubusercontent.com/assets/6467569/9858989/c234314a-5ad8-11e5-9996-3b7e5875964f.png)

**Comment by surajpindoria** [comment]
![screenshot_2015-09-14-12-08-48](https://cloud.githubusercontent.com/assets/6467569/9859193/1c9c9810-5ada-11e5-886e-bb68b8ae5afc.png)

**Comment by mwbrooks** [comment]
Looks awesome! How does WP8 look?

**Comment by surajpindoria** [comment]
![wp_ss_20140208_0007](https://cloud.githubusercontent.com/assets/6467569/9861193/afbca83c-5ae5-11e5-917e-d8499ee6f9c6.png)

**Comment by mwbrooks** [comment]
Nice. I'm happy. Let's close off this issue. When @hollyschinsky has a chance, she can review the images and ensure they are acceptable as well.
