### ISSUE TITLE
Phonegap serve on android 5.0

### ISSUE THREAD

**Issue by cobyl** [phonegap/phonegap-app-developer#340]
I have problem with Adobe Google Play Application - i use that great tool "phonegap serve". And when i develop my application on android 4.* everything works fine - but when i run it on android 5.0 just after upload my phonegap app to Phonegap Google Play Application i get just white screen.

This is what i see in android sdk debuger:

08-27 10:33:02.366: I/chromium(9770): [INFO:CONSOLE(247)] "Uncaught ReferenceError: io is not defined", source: file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/index.html (247)

08-27 10:33:02.406: I/chromium(9770): [INFO:CONSOLE(140)] "Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;
I don't use any 'socket.io' in my application - as i guess this is thing added by adobe phonegap app to maintain things like app refresh. So i try "phonegap serve --no-autoreload" but this not helps.

Oh, and one more important, the last thing - when i build application to apk - everythings work ok on android 5.

**Comment by nkmohanraju** [comment]
Hi Cobyl,

I am facing same issue. did you find any solution for this?


kind-regards
krishan

**Comment by cobyl** [comment]
yes. this plugin is solution. https://www.npmjs.com/package/cordova-plugin-crosswalk-webview thanks to it you have always same version of webview.

**Comment by nkmohanraju** [comment]
Thanks you very much friend for quick response.it really helps me to solve it. actually i am completely stuck up with this issue. now i can go ahead for next tasks.

Kind-Regards
krishna (india)

**Comment by surajpindoria** [comment]
This issue looks like it was resolved, closing it out.
