### ISSUE TITLE
Audit config.xml <preference> Values

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#344]
A lot of various preferences have crept into the app. Let's audit each and ensure that they are both needed and correct.

**Comment by timkim** [comment]
I found this particular one today while wrestling with the splash screen for wp8:
`<preference name="AutoHideSplashScreen" value="false" />`

Leaving this set to `false` causes the splash screen on wp8 to flicker (ie, opens app to black, switches to grey, then black, then to the loading screen). Quite annoying. I'm not even sure we need this for the other platforms either?

**Comment by timkim** [comment]
Or actually - it seems like it still flickers regardless of setting it to either true or false??? Will have to investigate more into this one.

**Comment by mwbrooks** [comment]
@surajpindoria feel free to remove any PGB-specific settings:
http://docs.build.phonegap.com/en_US/
