### ISSUE TITLE
The built version of WP8 is wrong in many places

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-app-developer#348]
When building the wp8 platform, a fair number of differences arise in the https://github.com/phonegap/phonegap-app-developer/blob/master/platforms/wp8/Properties/WMAppManifest.xml file. 

Here are the tags/settings that are incorrect:
- `<App Description="Adobe Phonegap Team">` should be  `Description="The PhoneGap Developer app is a testing utility for web developers and designers using the PhoneGap framework. After installing this app on your device you will be able to connect it to the PhoneGap desktop app to instantly view and test your work."`
- `<App ProductID>`  has a different hash 
- `<App Title="PhoneGap">` should be `Title="PhoneGap Developer"` 
- `<PrimaryToken TokenID="PhoneGapToken">` should be `TokenID="PhoneGap"`
- Show default phonegap app icon
- Shows app default phonegap splash screen

**Comment by timkim** [comment]
It appears that `<App ProductID />` having a different hash is ok. It's a GUID:
```
ProductID

The default value is the GUID for the project (128 bit). During the app submission process, a new product ID is inserted into the manifest file.
```
From: https://msdn.microsoft.com/en-us/library/windows/apps/ff769509(v=vs.105).aspx

**Comment by timkim** [comment]
I decided to keep the `Product ID` the same - may as well keep it the same.

**Comment by mwbrooks** [comment]
Nice
