### ISSUE TITLE
Can't use custom plugin cordova-sqlite-storage

### ISSUE THREAD

**Issue by screendriver** [phonegap/phonegap-app-developer#360]
I try to install a [custom plugin](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins)

```sh
$ cordova plugin add cordova-sqlite-storage --save
```

After that I run

```sh
$ npm run phonegap -- run android
```

I the following output I can see 

```sh
...
Fetching plugin "phonegap-plugin-contentsync@~1.1.3" via npm
Fetching plugin "cordova-plugin-whitelist@~1.0.0" via npm
Fetching plugin "com.megster.cordova.ble@~0.1.9" via npm
Fetching plugin "io.litehelpers.cordova.sqlite@~0.7.10" via npm
...
```

so I guess it's installing `io.litehelpers.cordova.sqlite`. But a few lines bellow I can't see a `installing "cordova-sqlite-storage" for android`. In my hello world application `window.sqlitePlugin` is undefined as well.

By the way: it is recommended to install the SQLite plugin with plugman. Unfortunately this does not work. See also #359

**Comment by surajpindoria** [comment]
Hi @screendriver,

Are you still seeing this? I have just tried on all platforms and am able to install and use the plugin. If you are, please go ahead and reopen the issue.

**Comment by screendriver** [comment]
With the latest version from `master` branch it seems to work :+1:
