### ISSUE TITLE
config.xml points to wrong plugin id for com.megster.cordova.ble

### ISSUE THREAD

**Issue by bhellema** [phonegap/phonegap-app-developer#361]
The plugin name change when the com.megster.cordova.ble was moved to npm.  

https://github.com/don/cordova-plugin-ble-central states:
"Note that this plugin's id changed from com.megster.cordova.ble to cordova-plugin-ble-central as part of the migration from the Cordova plugin repo to npm."

The config.xml should flip over to use the new plugin name.

https://github.com/phonegap/phonegap-app-developer/blob/master/config.xml#L42

**Comment by mwbrooks** [comment]
Nice catch @bhellema! You're on the ball.

We've actually patched this in the `ios9-upgrade` branch, which is waiting for app store approval. Once it's approved, we'll merge it into `master`:
https://github.com/phonegap/phonegap-app-developer/blob/ios9-upgrade/config.xml#L42

If you're building the app yourself for iOS, I'd recommend using that branch!

Thanks for heads up on the config issue. Keep 'em coming!
