### ISSUE TITLE
Clicks not working on my Landing page in PhoneGap App

### ISSUE THREAD

**Issue by sidn041** [phonegap/phonegap-app-developer#362]
HI,
I am new to app build, I am modifying an app I bought it from a developer, 

My app get stuck at landing page and clicks doesn't work, on speaking to the developer I was told it's limitation of phonegap desktop app on windows platform, as it won't support 3rd party plugin.
I tried by adding plugins externally using "Cordova plugin add" but no luck yet.

config.xml have with following plugins.

```
<gap:plugin name="org.apache.cordova.geolocation"  source="pgb" version="0.3.7" />
    <gap:plugin name="com.ionic.keyboard" source="pgb" version="1.0.3" />
    <gap:plugin name="org.apache.cordova.device" source="pgb" version="0.2.12" />
    <gap:plugin name="org.apache.cordova.device-orientation" source="pgb" version="0.3.9" />
    <gap:plugin name="org.apache.cordova.dialogs" source="pgb" version="0.2.10" />
    <gap:plugin name="org.apache.cordova.file-transfer" source="pgb" version="0.4.6" />
    <gap:plugin name="org.apache.cordova.inappbrowser" source="pgb" version="0.5.2" />
    <gap:plugin name="org.apache.cordova.network-information" source="pgb" version="0.2.12" />
    <gap:plugin name="org.apache.cordova.splashscreen" source="pgb" version="0.3.4" />
```

**Comment by surajpindoria** [comment]
Hi @sidn041,

Since we now use npm scripts for the project, simply running PhoneGap/Cordova commands will not work properly. Please follow [these] (https://github.com/phonegap/phonegap-app-developer/issues/372#issuecomment-159705782) steps in order to add a 3rd party plugin to the app.

**Comment by purplecabbage** [comment]
considering this answered.
