### ISSUE TITLE
Windows phone 8 - app doesn't work correctly, but works correctly on ios and android

### ISSUE THREAD

**Issue by GavinClarke** [phonegap/phonegap-app-developer#364]
Hello, 
The app i am creating needs to make an xhr call, it works on ios and android but it does not work on windows phone 8. that is not the only problem, when i remove the xhr calls it does not make it into methods that run correctly, on the other two devices. 

-----------------------first problem - xhr call-----------------------------------
Net.prototype.loadHtml = function( assetManager, filename, name, downloadCallback) 
{
    alert("loading " + filename);
    var jsonfile = new XMLHttpRequest();
    jsonfile.open("GET", filename, true);
    jsonfile.onload = function() 
    {  
        assetManager.templates[name] = jsonfile.responseText;
        assetManager.filesLoaded++;

```
    alert("loaded " + name);
    if(assetManager.numberOfFiles === assetManager.filesLoaded)
    {
        downloadCallback();
    }   
};
jsonfile.send(null);
```

}
-------------------------not calling methods---------------------------------------------------
function LoginView(controller)
{
    this.title = "loginView";
    this.controller = controller;
    this.loginDiv;
    this.loadDiv;
    this.successDiv;
    alert("calling setup");
    this.setup(); <--- errors here
}

LoginView.prototype.setup = function()<----- doesn't make it into this method
{
    alert("in setup");
    var that = this;
    if(!this.init)
    {
        //call standard setup for every view
        View.prototype.setup.call(this);
        this.getHTML();
        this.addEvents();
    }

}

**Comment by mwbrooks** [comment]
@GavinClarke Windows Phone can be a tricky platform, since it uses the Internet Explorer webview instead of Webkit.

For your XHR issue, can you try changing the `.onload` to `.onreadystatechange`? I use this method in code shared between Android, iOS, and WP and it's worked well for the past few years.

```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET', url, true);
// I don't remember why I have this method, but it may have fixed a WP issue
xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
xhr.onreadystatechange = function() {
    // readyState is done and there was a 2XX response code status
    if (this.readyState === 4 && /^[2]/.test(this.status)) {
        var response = JSON.parse(this.responseText);
        // Add your code here...
    }
};
xhr.send();
```

**Comment by GavinClarke** [comment]
that worked thanks very much

**Comment by mwbrooks** [comment]
Great to hear @GavinClarke!

**Comment by GavinClarke** [comment]
any idea why the other problem might be happening?

**Comment by mwbrooks** [comment]
Off the top of my head, no. I would expect `this` to belong to the `LoginView` instance.

Can you provide a complete example, that recreates the issue, that I can load onto a Windows Phone for testing?

**Comment by GavinClarke** [comment]
yeah where could i send it to you?

**Comment by GavinClarke** [comment]
does wp8 have a problem with inheritance when used in javascript?

**Comment by GavinClarke** [comment]
LoginView.prototype = Object.create(View.prototype) also i thought this might be a cause

**Comment by GavinClarke** [comment]
tested it and it seems to be the prototype functions, because it can all global functions, though it can call prototype functions in on other objects

**Comment by purplecabbage** [comment]
considering this answered. the other js problems appear to be simple misunderstanding of js prototype  object chains.  WP8 is long gone now, Windows 10 features more modern js features and implements the same standard as chrome, and safari.
