### ISSUE TITLE
my app is not installed on windows phone

### ISSUE THREAD

**Issue by Diwakarreddy15** [phonegap/phonegap-app-developer#367]
while i was trying to  install .xap file in to the windows phone it was showing company app is not installed. Is there any possibility to test my app in windows phone.

**Comment by mwbrooks** [comment]
Hi @Diwakarreddy15,

On Windows Phone, you need to install XAP using Visual Studio or `XapDeploy.exe`. Usually if you try to install it using another approach (e.g. pointing your mobile browser to a host `.xap` file) then you'll receive the "company app is not installed" error message.

You learn more about `XapDeploy.exe` here:
https://msdn.microsoft.com/en-us/library/windows/apps/ff402565(v=vs.105).aspx

**Comment by Diwakarreddy15** [comment]
thanks mwbrooks
