### ISSUE TITLE
The deviceready event does not fire in a developer app built locally from master

### ISSUE THREAD

**Issue by blefebvre** [phonegap/phonegap-app-developer#370]
I'm building phonegap-app-developer from source so I can add a few plugins that my app needs. When I build from source, the app starts up fine but the `deviceready` event never appears to fire for the app that it loads. I do not see this issue when I use the iOS app available in the App Store.

To reproduce, first build and run the developer app:
```
$ cd phonegap-app-developer/
$ npm install
$ npm run phonegap -- run ios
```

Next, use the PhoneGap CLI to initialize a new app:
```
$ cd ~/workspace/temp/
$ phonegap create my-app-2
$ cd my-app-2/
$ phonegap serve
```

Next, connect to the local server using the developer app (I used `127.0.0.1:3000` since I was running on the iOS Simulator).

Result:
The `deviceready` event never appears to fire [0].

Environment:

- OS X 10.10.5
- Xcode 7.1.1
- iPhone 6 iOS 9.1 Sim 
- node v0.12.2
- npm 2.13.3
- PhoneGap CLI 5.3.7

[0] 
![screen shot 2015-11-17 at 12 28 51 pm](https://cloud.githubusercontent.com/assets/1048207/11218981/ea08ee52-8d25-11e5-8eee-6e5f316da1eb.png)

**Comment by surajpindoria** [comment]
Hi @blefebvre, we were also seeing this issue yesterday and have already begun to investigate.

**Comment by benjasHu** [comment]
Hi @surajpindoria any news on this issue? I'm having same problems...

Thanks for helping.

**Comment by surajpindoria** [comment]
This has been resolved on the latest `dev` branch @blefebvre
