### ISSUE TITLE
Uncaught module com.pushwoosh.plugins.pushwoosh.PushNotification not found

### ISSUE THREAD

**Issue by virodh** [phonegap/phonegap-app-developer#371]
hello guys ,
i am using ah phonrgap for the push notifcation plugin 
In the console i got a error that 

"Uncaught module com.pushwoosh.plugins.pushwoosh.PushNotification not found"

function initPushwoosh() {

	var pushNotification = cordova.require("com.pushwoosh.plugins.pushwoosh.PushNotification");

	//set push notifications handler
	document.addEventListener('push-notification',
		function(event)
		{
            var title = event.notification.title;
            var userData = event.notification.userdata;

            //dump custom data to the console if it exists
            if(typeof(userData) != "undefined") {
				console.warn('user data: ' + JSON.stringify(userData));
			}

			//and show alert
			alert(title);

			//stopping geopushes
			//pushNotification.stopGeoPushes();
		}
	);

	//initialize Pushwoosh with projectid: "GOOGLE_PROJECT_ID", appid : "PUSHWOOSH_APP_ID". This will trigger all pending push notifications on start.
	pushNotification.onDeviceReady({ projectid: "785229330087", appid : "B89CF-8C973" });

	//register for push notifications
	pushNotification.registerDevice(
		function(token)
		{
			alert(token);
			//callback when pushwoosh is ready
			onPushwooshAndroidInitialized(token);
		},
		function(status)
		{
			alert("failed to register: " +  status);
		    console.warn(JSON.stringify(['failed to register ', status]));
		}
	);
}

function onPushwooshAndroidInitialized(pushToken)
{
	//output the token to the console
	console.warn('push token: ' + pushToken);

	var pushNotification = cordova.require("com.pushwoosh.plugins.pushwoosh.PushNotification");
	
	//if you need push token at a later time you can always get it from Pushwoosh plugin
	pushNotification.getPushToken(
		function(token)
		{
			console.warn('push token: ' + token);
		}
	);

	//and HWID if you want to communicate with Pushwoosh API
	pushNotification.getPushwooshHWID(
		function(token) {
			console.warn('Pushwoosh HWID: ' + token);
		}
	);
	
	pushNotification.getTags(
		function(tags)
		{
			console.warn('tags for the device: ' + JSON.stringify(tags));
		},
		function(error)
		{
			console.warn('get tags error: ' + JSON.stringify(error));
		}
	);
	 

	//set multi notificaiton mode
	//pushNotification.setMultiNotificationMode();
	//pushNotification.setEnableLED(true);
	
	//set single notification mode
	//pushNotification.setSingleNotificationMode();
	
	//disable sound and vibration
	//pushNotification.setSoundType(1);
	//pushNotification.setVibrateType(1);
	
	pushNotification.setLightScreenOnNotification(false);
	
	//setting list tags
	//pushNotification.setTags({"MyTag":["hello", "world"]});
	
	//settings tags
	pushNotification.setTags({deviceName:"hello", deviceId:10},
		function(status) {
			console.warn('setTags success');
		},
		function(status) {
			console.warn('setTags failed');
		}
	);

	//Pushwoosh Android specific method that cares for the battery
	//pushNotification.startGeoPushes();
}
function initPushwoosh() {

	var pushNotification = cordova.require("com.pushwoosh.plugins.pushwoosh.PushNotification");

	//set push notifications handler
	document.addEventListener('push-notification',
		function(event)
		{
            var title = event.notification.title;
            var userData = event.notification.userdata;

            //dump custom data to the console if it exists
            if(typeof(userData) != "undefined") {
				console.warn('user data: ' + JSON.stringify(userData));
			}

			//and show alert
			alert(title);

			//stopping geopushes
			//pushNotification.stopGeoPushes();
		}
	);

	//initialize Pushwoosh with projectid: "GOOGLE_PROJECT_ID", appid : "PUSHWOOSH_APP_ID". This will trigger all pending push notifications on start.
	pushNotification.onDeviceReady({ projectid: "785229330087", appid : "B89CF-8C973" });

	//register for push notifications
	pushNotification.registerDevice(
		function(token)
		{
			alert(token);
			//callback when pushwoosh is ready
			onPushwooshAndroidInitialized(token);
		},
		function(status)
		{
			alert("failed to register: " +  status);
		    console.warn(JSON.stringify(['failed to register ', status]));
		}
	);
}

function onPushwooshAndroidInitialized(pushToken)
{
	//output the token to the console
	console.warn('push token: ' + pushToken);

	var pushNotification = cordova.require("com.pushwoosh.plugins.pushwoosh.PushNotification");
	
	//if you need push token at a later time you can always get it from Pushwoosh plugin
	pushNotification.getPushToken(
		function(token)
		{
			console.warn('push token: ' + token);
		}
	);

	//and HWID if you want to communicate with Pushwoosh API
	pushNotification.getPushwooshHWID(
		function(token) {
			console.warn('Pushwoosh HWID: ' + token);
		}
	);
	
	pushNotification.getTags(
		function(tags)
		{
			console.warn('tags for the device: ' + JSON.stringify(tags));
		},
		function(error)
		{
			console.warn('get tags error: ' + JSON.stringify(error));
		}
	);
	 

	//set multi notificaiton mode
	//pushNotification.setMultiNotificationMode();
	//pushNotification.setEnableLED(true);
	
	//set single notification mode
	//pushNotification.setSingleNotificationMode();
	
	//disable sound and vibration
	//pushNotification.setSoundType(1);
	//pushNotification.setVibrateType(1);
	
	pushNotification.setLightScreenOnNotification(false);
	
	//setting list tags
	//pushNotification.setTags({"MyTag":["hello", "world"]});
	
	//settings tags
	pushNotification.setTags({deviceName:"hello", deviceId:10},
		function(status) {
			console.warn('setTags success');
		},
		function(status) {
			console.warn('setTags failed');
		}
	);

	//Pushwoosh Android specific method that cares for the battery
	//pushNotification.startGeoPushes();
}

**Comment by surajpindoria** [comment]
Hi @virodh,

It seems that the `com.pushwoosh.plugins.pushwoosh` plugin is not properly installed. Can you try reinstalling the plugin and seeing if that changes anything. I also found some [sample code](https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample) that may help you.

**Comment by surajpindoria** [comment]
I am going to close this issue, if you are still having this problem feel free to reopen it.

**Comment by jlstr** [comment]
Hello @surajpindoria, I'm having the same issue (inside XCode), This is my list of plugins:
```
$ cordova plugin list
com.ionic.keyboard 1.0.2 "Keyboard"
com.transistorsoft.cordova.background-geolocation 0.6.4 "BackgroundGeolocation"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-camera 1.2.0 "Camera"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-geolocation 1.0.0 "Geolocation"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
org.apache.cordova.console 0.2.10 "Console"
org.apache.cordova.device 0.2.11 "Device"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"
pushwoosh-cordova-plugin 4.2.2 "
		This plugin allows you to send and receive push notifications. Powered by Pushwoosh (www.pushwoosh.com).
```

Does the above seem to you like the plugin is correctly installed? My app is an Ionic App. I am following this sample app: https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample/tree/master/Ionic

One additional question: For an Ionic App aimed for iOS, Do I need more JavaScript libraries other than this one: https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample/blob/master/Ionic/www/js/PushwooshiOS.js

Thanks in advance for your help.

**Comment by adriangordon1231** [comment]
I am having the exact same issue

**Comment by adriangordon1231** [comment]
@jlstr 

Try changing

var pushNotification = cordova.require("com.pushwoosh.plugins.pushwoosh.PushNotification");

to 

var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");

**Comment by jlstr** [comment]
@adriangordon1231 Precisely. That did it for me as well. Thank you very much!

**Comment by arielweinberger** [comment]
Just a note for people who encounter this problem in the future too.
In PushWoosh's sample app, they require the "com.pushwoosh.plugins.pushwoosh.PushNotification" cordova plugin.

In the documentation, they use "pushwoosh-cordova-plugin.PushNotification".

Make sure to `ionic plugin install` the right one. As far as I remember, `pushwoosh-cordova-plugin.PushNotification` is the latest one.
