### ISSUE TITLE
wp8 xml http request sending but not recieving anthing back

### ISSUE THREAD

**Issue by GavinClarke** [phonegap/phonegap-app-developer#374]
Hello, i am having trouble with xhr calls on Wp8, now this code work correctly and i get responses on ios and android. i have no idea why this is happening no errors are thrown. any ideas will be much appreciated, i don't think it is a server problem because it is receiving and responding to ios and android. 

Net.prototype.send = function (type, url, formData, callback,token) 
{
	var xhr = new XMLHttpRequest();
	xhr.onreadystatechange = function() 
	{
	    if (xhr.readyState === 4) 
		{
            callback(xhr.responseText);
	    }
	}
	xhr.open(type, url, true);
    if(typeof token != 'undefined')
    {
        xhr.setRequestHeader('x-zumo-auth', token);
    }
    if(formData !== null)
    {
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.setRequestHeader('Content-Length', formData.length);
    }
	xhr.send(formData);
};

**Comment by timkim** [comment]
Hi @GavinClarke 

It looks like your code is correct to me. I also tried to use the code above (with a few things modified) and I can at least successfully ping my own server. 

My guess is that perhaps it's not setting the auth token properly in wp8? Have you checked the server logs to see if at least a request was made by the wp8?

**Comment by GavinClarke** [comment]
yeah i discovered what the problem was it was the onreadystatechange method i had to change it to the onload method and this worked, i don't know why but it did

**Comment by timkim** [comment]
@GavinClarke Hrm, weird. Well, glad to hear it works!
