### ISSUE TITLE
Loading screen says 'Loadings...'

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-app-developer#375]
Whatever that means ...

<img width="277" alt="screen shot 2015-11-24 at 10 44 54 am" src="https://cloud.githubusercontent.com/assets/46134/11377002/b345be86-9298-11e5-9a67-affc13195b11.png">

**Comment by mwbrooks** [comment]
Looks like it's in some of the newer splash images. I can fix it.

**Comment by mwbrooks** [comment]
See commit d954fb9 for the updated splashscreens.
