### ISSUE TITLE
web api is not calling from jquery but it is called from postman 

### ISSUE THREAD

**Issue by Diwakarreddy15** [phonegap/phonegap-app-developer#376]
iam tying to call web api  by  using the juery ajax method but it was not showing anything . please let me how can i resolve the problem

**Comment by surajpindoria** [comment]
Hi @Diwakarreddy15,

Can you provide some sample code as well as the versions of PhoneGap and the Developer App that you are using?

**Comment by Diwakarreddy15** [comment]
$.ajax({
 url:'http://astro.preprod.co.in/api/values',
type:'GET',
data: empdeatails,
dataType: 'jsonp',
crossDomain: true,
success: function (data) {
console.log(data.msg);							
},
						 error: function (xhr) {
							alert(xhr.responseText);
						}
						});
iam using phonegap cli 5.3.6 version and am using developer app to test the felilds

**Comment by surajpindoria** [comment]
I am able to run the jQuery Ajax method on my machine. Are you making sure to include jQuery within `index.html` @Diwakarreddy15

**Comment by Diwakarreddy15** [comment]
ya i have included jquery in index.html

**Comment by Diwakarreddy15** [comment]
can you provide some sample code to test my application @surajpindoria

**Comment by surajpindoria** [comment]
```javascript
$.ajax({
    url: 'http://astro.preprod.co.in/api/values',
    type: 'GET',
    dataType: 'json',
    success: function(result) {
        console.log(result);
    }
});
```

I found that I was having problems when trying to set `dataType: 'jsonp'`, the [jQuery docs](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings) talk a little bit about issues with jsonp and cross domain requests. Maybe this is what you are seeing @Diwakarreddy15
