### ISSUE TITLE
Determine what events we'd like to track for analytics

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap-app-developer#379]
Device ready, connection attempt, connection success, connection failure, opening the app, changing IP address of the app, etc.

**Comment by timkim** [comment]
Events that correspond to the connection/error status that the content sync plugin returns: https://github.com/phonegap/phonegap-plugin-contentsync#contentsyncprogress_state and https://github.com/phonegap/phonegap-plugin-contentsync#contentsyncerror_state

Might get some good insight as to where the plugin is failing for some people.

**Comment by timkim** [comment]
Are we set on the events we are tracking right now? 

So far we have:
- startup
  - deviceready
- connection
  - cancelled
  - download
  - extract
  - success
  - failure
    - invalid url
    - unable to connect
    - unable to unzip

**Comment by timkim** [comment]
Guess we're good with these!
