### ISSUE TITLE
Phonegap Developer App Custom IOS Build

### ISSUE THREAD

**Issue by mehraaad** [phonegap/phonegap-app-developer#381]
I am trying to create a custom build for phonegap app for ios.
After installing node.js and npm, I did the following in mac terminal:

$ git clone https://github.com/phonegap/phonegap-app-developer.git
$ cd phonegap-app-developer/
$ npm install

due to some permission errors, I decided to do the following:

$sudo chmod -R 777 phonegap-app-developer/

and after that:

$ npm run phonegap -- build ios

After running the above line, the process of building starts and ends with the following message:

** BUILD SUCCEEDED **
Command finished with error code 0: /Users/user/Desktop/phonegap/phonegap-app/phonegap-app-developer/platforms/ios/cordova/build 
[phonegap] completed 'cordova --verbose build ios'

After this step I go to "platforms" folder and then into "ios" and then I open the xcodeproj file, change app identity and then install the app on my phone. (with the latest version of xcode I can install my projects on my phone without a developers account)
after creating a new project and serving it, I open the app and connect to server successfully.
But the "deviceready" event never gets fired!!!
I also conenct to this server with an android device and It works just fine. So there is something wrong with the custom app I just built.
Also the original phonegap app (that I downloaded from appstore) works fine.

Can anybody help me with this issue?

**Comment by surajpindoria** [comment]
Hi @mehraaad, this issue has been resolved in the `dev` branch. You can checkout that branch and build from there, but we will be merging this branch back into `master` later today.
