### ISSUE TITLE
compatibility issues in android version kitkat 4.4.4 while uploading images from photolibrary

### ISSUE THREAD

**Issue by Diwakarreddy15** [phonegap/phonegap-app-developer#383]
iam using kitkat 4.4.4, while testing my apps it was showing unfortunately stopped. I have checked in  lollypop  5.0 it works fine, then i got to know that this is issue from the  compatibility of the android versions. How can i resolve problem.
thanking you in advance

**Comment by surajpindoria** [comment]
Hi @Diwakarreddy15,

I have just tested this on both versions of Android and did not have any problems. Can you please tell me what your versions of PhoneGap and the Developer App are?

**Comment by Diwakarreddy15** [comment]
Hi suraj
  Thanks for ur information, i have added  kitkat issues plugins into config.xml. The problem has been fixed and it is working fine for the independent of  version .

**Comment by surajpindoria** [comment]
Ok great! I am going to go ahead and close this issue out then
