### ISSUE TITLE
Unable to properly unzip the archive

### ISSUE THREAD

**Issue by reueljonathan** [phonegap/phonegap-app-developer#385]
Well, I didn't found any answers in others issues here, so I'm creating one. I'm trying test one game in windows phone 8.1, but when I try to test with the phonegap developer app, I receive this error:

> " Alert
  Unable to download archive from the server.
  Unable to properly unzip the archive."

So I created the hello-world app and the same error occurs, but in an Android phone my game and the hello-world app work fine.
I also tried to download the zip via browser ( x.x.x.x:3000/\__api\__/appzip ), and it cames without the _.zip_ extension. This matters?

Here are what I use:

* OS: Windows 8.1
* Phonegap Version: 5.3.9
* Cordova Version: 5.4.1
* Windows Phone Version: 8.10.14219.341
* Android phone version: 5.0.2

**Comment by surajpindoria** [comment]
Hi @reueljonathan,

I have just looked into this and I do believe it is a bug on the windows side. When downloading the zip on OS X the file does come with the `.zip` extension.

**Comment by reueljonathan** [comment]
Hi @surajpindoria, that's it. I tried the link in chrome on android and it cames with the `.zip`. Thanks for the help. =]

**Comment by surajpindoria** [comment]
Ok great! After further investigation I do not believe that the lack of `.zip` extension is a bug. Downloading the archive on different browsers has varying results. I am going to close this out @reueljonathan
