### ISSUE TITLE
console.assert() not working, causing Angular 2 crash

### ISSUE THREAD

**Issue by woutervandergraaf** [phonegap/phonegap-app-developer#386]
Please make all window.console methods available in the Phonegap Developer App, e.g. console.assert().

This gets injected in my app's index.html by the Phonegap Developer App:

```html
<script type="text/javascript" src="http://192.168.1.16:3000/socket.io/socket.io.js"></script>
<script type="text/javascript">
(function(window) {
    var socket = io('http://192.168.1.16:3000');
    var previousConsole = window.console || {};
    window.console = {
        log:function(msg){
            previousConsole.log && previousConsole.log(msg);
            socket.emit('console','log', msg);
        },
        warn:function(msg){
           previousConsole.warn && previousConsole.warn(msg);
            socket.emit('console','warn', msg);
        },
        error:function(msg){
            previousConsole.error && previousConsole.error(msg);
            socket.emit('console','error', msg);
        }
    }
})(window);
</script>
```

It intercepts window.console. However, Angular 2.0 calls console.assert at some point, which isn't provided in the overwritten console object.

**Comment by surajpindoria** [comment]
I am able to get `console.assert` to work on iOS occasionally, but not on Android. It works just fine on both platforms when installing to the device. Will continue to investigate this issue on the Dev App.

**Comment by doctorrustynelson** [comment]
+1

**Comment by timkim** [comment]
Ok, the fix is in thanks to @doctorrustynelson. 

Just update `phonegap` with `npm install -g phonegap` or make sure install the latest `connect-phonegap`.

**Comment by mwbrooks** [comment]
Thanks for taking care of this @timkim! And thanks @doctorrustynelson for the addition - it's awesome!
