### ISSUE TITLE
ble plugin not working in galaxy s6

### ISSUE THREAD

**Issue by cajay01** [phonegap/phonegap-app-developer#390]
I use megster version 0.1.2 as a ble plugin for phone gap application to connect to ble devices.Using this plugin I can connect to device in galaxy S5 having android version 4.4.2 but I am getting problem in Galaxy S6 having version 5.1.1.
I use same pluging in different android versions it works fine their who supports BLE.
Is there any problem related to S6 and ble plugin

**Comment by surajpindoria** [comment]
Hi @cajay01,

That version of the BLE plugin is no longer available or supported on npm. We have updated the version used on the dev app, `cordova-plugin-ble-central@1.0.1`. Maybe using this version will help to solve your problem. Please let me know if this helps.

**Comment by cajay01** [comment]
Thank you Suraj I will try with it

**Comment by cajay01** [comment]
Hey Suraj I tried with new plugin but its not working even on other devices where previous plugin was working correctly

**Comment by cajay01** [comment]
Hey Suraj I tried with new plugin but its not working even on other devices where previous plugin was working correctly

**Comment by cajay01** [comment]
Is there any specific cordova-ionic version supposed to use with this plugin?

**Comment by surajpindoria** [comment]
As far as I can tell, there are no restrictions on the cordova/ionic version. I will continue to investigate this further.

**Comment by surajpindoria** [comment]
I have looked more into this, as far as I can tell it doesn't seem to be a problem with the developer app. This may be a problem with the BLE plugin. I am going to close this issue. @cajay01
