### ISSUE TITLE
Phone gap with angular.js not connecting my localhost database using xampp server 

### ISSUE THREAD

**Issue by meerpanhyar** [phonegap/phonegap-app-developer#398]
Hello everyone .
I'm new to phone gap , i'm trying to connect my phone gap app with localhost database , everything is fine on localhost , but when i test it on the phone gap desktop testing service , i'm unable to save my data on localhost database .

below is my code to store data on localhost 
`
var app = angular.module('app', []);
app.controller('meerChat', ChatFunction);

function ChatFunction($scope,$http) {
      $http.post("pathtomylocalg=host",{'para1': val1, 'para2': val2})
            .success(function(data, status, headers, config){
            });
        }
}`

**Comment by surajpindoria** [comment]
Seems similar to #335

**Comment by purplecabbage** [comment]
This sounds to be a permissions issue.  What does your content security policy state?
Be sure that the server is reachable from the device, can a browser on the phone open the hosted site?
Please reopen if this is still an issue, and you can provide more details.
