### ISSUE TITLE
Issues while uploading a video to the server

### ISSUE THREAD

**Issue by Diwakarreddy15** [phonegap/phonegap-app-developer#399]
To uploading a video to the server, it is taking around 3 to 4 minutes for uploading small (4 to 5 seconds) video. Can you please give me some suggestions for the compression techniques in video format  and i need progress bar while  uploading a video through web API. Another issue is for example  first time it is uploading a video to the server and for the second time it will show error status, means for every new attempt first time it will successfully uploading to the server and  for second time  it is showing errors.

Thanking you

**Comment by surajpindoria** [comment]
Can you try uploading the video with the app installed on the device? @Diwakarreddy15

**Comment by Diwakarreddy15** [comment]
yes, I had installed into device same issue.

**Comment by surajpindoria** [comment]
I do not have much experience with video compression myself. Maybe one of these resources will be helpful for you. @Diwakarreddy15 

[HTML5 Video Basics](http://www.html5rocks.com/en/tutorials/video/basics/)
[MDN Media Formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats)
