### ISSUE TITLE
Unable to download and install Developer from the Play Store (Reference Post)

### ISSUE THREAD

**Issue by synfrag** [phonegap/phonegap-app-developer#408]
Posted also on the Adobe Builder forum but I'm providing this here as well. I don't know enough about the issue to tell if this is intentional on the manufacturer's side or if it's an oversight somewhere.

PhoneGap Developer is listed as incompatible with the FUHU Big Tab requiring a manual download and install of the APK instead. The device runs on Android 4.4.2 and as far as I can tell thus far the Developer App appears to work just fine when installed.

![screenshot_2016-03-01-13-17-10](https://cloud.githubusercontent.com/assets/15794305/13442561/1e4a8ac2-dfba-11e5-9f1e-3fbccfb9488f.png)

**Comment by surajpindoria** [comment]
Hi @synfrag,

I double checked and we have included all devices in the Google Play Store. I ran a search and the Store does not have an option for your device, only for the Fuhu DreamTab. Not sure if this is an issue you are facing with other apps.

**Comment by synfrag** [comment]
@surajpindoria ,

Surprisingly, PhoneGap is the only app I've run into thus far on this device that would not allow an install. I decided to hunt around for a few minutes and I was unable to find another app with the issue. I realize this probably isn't great help, I'm very new to mobile development.

**Comment by surajpindoria** [comment]
@synfrag,

After investigating further, I did manage to find your device but was unable to add it because it is marked as unsupported. These devices are marked based on the hardware requirements / preferences we set within the app, unfortunately your device fails to meet one of these. Hopefully your workaround allows you to use the app to your needs, but it may not work with full functionality.

Going to close this issue.

**Comment by Zarkonnen** [comment]
Could you please publish the set of hardware requirements/preferences for the app? I am rather surprised that it doesn't work on my Samsung SM-G355H with Android 4.4.2. I can buy another phone to do development on, but with no way of telling what phones are supported, I don't know how to pick one that will work!

**Comment by abdallah-amoudi** [comment]
Hi,
@surajpindoria can you give us the link where I can see the list of supported Android devices for phonegap app

**Comment by surajpindoria** [comment]
Hi @abdallah-amoudi and @Zarkonnen,

Sorry for going quiet on this post. Google's app compatibility is all based on the Android Manifest and currently ours is very inclusive, so not sure why so many devices are considered unsupported on the Play Store. Also there doesn't seem like an easy way to export the list of supported devices from Google.

We are currently looking into this and will hopefully be able to uncover something soon.

**Comment by surajpindoria** [comment]
So unfortunately there isn't a whole lot we can do in terms of adding to the list of supported devices. As we add features and plugins to the developer app the requirements needed will continue to change. Here is a list of the current software, hardware, and permissions required:

**API Levels Supported**

- 15+

**Hardware Requirements**

- android.hardware.BLUETOOTH
- android.hardware.CAMERA
- android.hardware.LOCATION
- android.hardware.location.GPS
- android.hardware.location.NETWORK
- android.hardware.MICROPHONE
- android.hardware.screen.LANDSCAPE
- android.hardware.sensor.ACCELEROMETER
- android.hardware.sensor.COMPASS
- android.hardware.TOUCHSCREEN
- android.hardware.WIFI

**Permissions Required**

- android.permission.ACCESS_COARSE_LOCATION
- android.permission.ACCESS_FINE_LOCATION
- android.permission.ACCESS_GPS
- android.permission.ACCESS_LOCATION_EXTRA_COMMANDS
- android.permission.ACCESS_NETWORK_STATE
- android.permission.ACCESS_WIFI_STATE
- android.permission.BLUETOOTH
- android.permission.BLUETOOTH_ADMIN
- android.permission.CAMERA
- android.permission.GET_ACCOUNTS
- android.permission.INTERNET
- android.permission.MODIFY_AUDIO_SETTINGS
- android.permission.READ_CONTACTS
- android.permission.READ_EXTERNAL_STORAGE
- android.permission.READ_PHONE_STATE
- android.permission.RECORD_AUDIO
- android.permission.RECORD_VIDEO
- android.permission.VIBRATE
- android.permission.WAKE_LOCK
- android.permission.WRITE_CONTACTS
- android.permission.WRITE_EXTERNAL_STORAGE
- com.google.android.c2dm.permission.RECEIVE

For those that are unable to install the current version from the Play Store, we do keep a copy of all released versions of the developer app [here](https://github.com/phonegap/phonegap-app-developer/tree/master/resources/release). You can download and install the version you need from there.

**Comment by Zarkonnen** [comment]
Thank you for taking your time to look into this. I understand that with phones so fragmented, you can't guarantee full coverage of every phone out there. :smile:

**Comment by biofsoares** [comment]
It is neither compatible with Samsung SM-G360BT, Android 5.0.2, **API level 21**. By the looks of previous posts, buying a new phone will not solve the problem. What are the other alternatives? Maybe a list of phones that ARE compatible would help.

**Comment by arnbme** [comment]
Based upon list of hardware requirements listed in an earlier post,  my HTC Desire 626 Android 5.1 is incompatible due to no compass! Phone also incompatible with most compass apps on play store.

**Comment by StJohn3D** [comment]
It's not compatible with my Samsung SM-G550T Android version 6.0.1. There are no updates available for my phone and I can't find another app (not even compass apps) that aren't compatible. It's certainly not the best phone in the world, but it should certainly be able to run the phonegap developer app easily.

**Comment by PFight** [comment]
Got this on Nexus 7. Installing from github apk solved the problem.

**Comment by Amaeta** [comment]
Phonegap is incompatible with my Techno Spark K7 Model mobile phones in playstore

**Comment by maniix123** [comment]
That's it, I'm done with this. I won't bother with this anymore, my phone's incompatible and I have been digging all around github links for solutions. This is too much of a hassle for a new app developer.

**Comment by DataScMx** [comment]
> So unfortunately there isn't a whole lot we can do in terms of adding to the list of supported devices. As we add features and plugins to the developer app the requirements needed will continue to change. Here is a list of the current software, hardware, and permissions required:
> API Levels Supported
> 
> 15+
> 
> Hardware Requirements
> 
> android.hardware.BLUETOOTH
> android.hardware.CAMERA
> android.hardware.LOCATION
> android.hardware.location.GPS
> android.hardware.location.NETWORK
> android.hardware.MICROPHONE
> android.hardware.screen.LANDSCAPE
> android.hardware.sensor.ACCELEROMETER
> android.hardware.sensor.COMPASS
> android.hardware.TOUCHSCREEN
> android.hardware.WIFI
> 
> Permissions Required
> 
> android.permission.ACCESS_COARSE_LOCATION
> android.permission.ACCESS_FINE_LOCATION
> android.permission.ACCESS_GPS
> android.permission.ACCESS_LOCATION_EXTRA_COMMANDS
> android.permission.ACCESS_NETWORK_STATE
> android.permission.ACCESS_WIFI_STATE
> android.permission.BLUETOOTH
> android.permission.BLUETOOTH_ADMIN
> android.permission.CAMERA
> android.permission.GET_ACCOUNTS
> android.permission.INTERNET
> android.permission.MODIFY_AUDIO_SETTINGS
> android.permission.READ_CONTACTS
> android.permission.READ_EXTERNAL_STORAGE
> android.permission.READ_PHONE_STATE
> android.permission.RECORD_AUDIO
> android.permission.RECORD_VIDEO
> android.permission.VIBRATE
> android.permission.WAKE_LOCK
> android.permission.WRITE_CONTACTS
> android.permission.WRITE_EXTERNAL_STORAGE
> com.google.android.c2dm.permission.RECEIVE
> 
> For those that are unable to install the current version from the Play Store, we do keep a copy of all released versions of the developer app here. You can download and install the version you need from there.

Can you please update the apk link? When I click on it, launches a 404 page. Thanks.

**Comment by marcckku** [comment]
SOLUTION .
The best solution for everybody that can not download phonegap developer from Google Play Store.
In my case I use Samsung Galaxy J2 device  and it's possible that execute in another version of Samsung Device I use Samsung Galaxy J5 or another ...!! 
GO TO LINK: https://phonegap-developer.apk.cafe/samsung/galaxy-j2  and download the last version apk phonegap for Android version 4 or greatest  for your samsung device.  In this moment 06/2019  the last version is:  "PHONEGAP DEVELOPER 1.8.4 for Samsung Galaxy J2 for ARM7 x86 devices
Android 4.4+ ".
IT'S THE BEST SOLUTION !!!!

**Comment by bustonshows** [comment]
So does it means that, the uploaded mobile app apk on wont appear at all on the playstore of the all the incompatible devices?

**Comment by lexycole** [comment]
Hello everybody, having same issues with _Phonegap developer app_ __not compatible with Itel s15__
