### ISSUE TITLE
Cross-domain POST request via JQuery AJAX call fails

### ISSUE THREAD

**Issue by ddramireddy** [phonegap/phonegap-app-developer#416]
I am calling a Cross-domain web service method via JQuery AJAX method. This method is of POST verb. This call is getting failed without any response.

In Developer tools in Chrome, I can see URL is going as 

**http://localwebsite/proxy/http://remotewebsite/restofurl**

But the URL i am calling is **http://remotewebsite/restofurl**. PhoneGap is appending the part "http://localwebsite/proxy/" to the URL. There is no issue in server-side. When tested with Chrome POSTMan or a separate HTML/JS file without PhoneGap, it's working fine.

What am i missing here?

**Comment by timkim** [comment]
Hi @ddramireddy 

In previous versions of the Developer App, we were proxying ajax requests so that they would get around a CORS issue. I would suggest updating the Developer App to the latest version as well as the PhoneGap CLI:
```
$ npm install -g phonegap
```

**Comment by ddramireddy** [comment]
Hi @timkim 

Thank you for your help. Even after running the above command, still I am getting the same error.  On entering the command "Phonegap -v", it showed version number as "6.1.0"

**Comment by ddramireddy** [comment]
Thanks @timkim 

It's working in Mobile app now. But on web browser, still the issue exists.

**Comment by surajpindoria** [comment]
Hey @ddramireddy,

The issue on the browser is due to legacy proxy code. It has been patched and will land in the next release of the CLI. Thanks for pointing it out!

**Comment by surajpindoria** [comment]
Fixed in [connect-phonegap](https://github.com/phonegap/connect-phonegap/commit/e264f2e03d86d8ad687a83855fff99a76c83f302)

**Comment by grippstick** [comment]
I have upgraded phonegap to 6.4.0. Is there something i need to do to make it use connect-phonegap?

when i serve locally and then execute: 
`            var xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange = function () {
                if (xhttp.readyState == 4 && xhttp.status == 200) {
                    console.warn('DONE');
                } else if (xhttp.readyState == 4 && xhttp.status !== 200) {
                    console.error('DEAD');
                }
            };
            xhttp.open("GET", "https://aligntoday.com", true);
            xhttp.send();`

it still 404's while trying to go to the proxy url of : http://10.50.3.64:3000/proxy/https%3A%2F%2Faligntoday.com
