### ISSUE TITLE
Error 505 when updating to latest (1.6.2) from the google play. Custom Phonegap app on google play also unable to install w/ 505 error.

### ISSUE THREAD

**Issue by elioair** [phonegap/phonegap-app-developer#417]
I am trying to update to the latest 1.6.2 phonegap developer app but the error code -505 message pops up. Also users of an app that I developed and is on google play reported the same error message and they are unable to download and install the app on different phones. 

P.S. Regarding the phonegap developer app others are having issues as well as I noticed. You can see the same error on a review from 26/4/2016 -screenshot:

![gplayphonegap](https://cloud.githubusercontent.com/assets/12306155/14827289/4feaff88-0bea-11e6-8531-f54354b458c3.png)

**Comment by macdonst** [comment]
@elioair hey, what is your app that is on the Google Play Store? Does it use phonegap-plugin-push?

**Comment by elioair** [comment]
@macdonst yes it does. [Here's](https://play.google.com/store/apps/details?id=com.fonitisydras.application) the app.

**Comment by macdonst** [comment]
@elioair okay, thanks that was very useful information as I was able to reproduce the problem as I can't install your app if I already have the PG Dev App installed. What version of phonegap-plugin-push do you use? I think it has to do with something I changed for MS.

**Comment by elioair** [comment]
@macdonst Thanks for looking into it. I'm not sure which version is been used tbh. I just declared it in the config.xml like this
```
 <plugin name="phonegap-plugin-push" source="npm">
        <param name="SENDER_ID" value="xxxx" />
    </plugin>
```

and built it in Phonegap Build on 18 April.

**Comment by macdonst** [comment]
@elioair thanks I believe I figured out what was going wrong. I had to release a new version of the push plugin to fix the problem. You should probably update your app to use version 1.6.3 as soon as you can. We'll end up releasing a new version of PG Dev App tomorrow.

**Comment by elioair** [comment]
@macdonst thanks a lot for your quick fix. I updated to version 1.6.3 of the push plugin and it installs without errors now, also the PG Dev app updates correctly. :+1:
