### ISSUE TITLE
Unable to compile & Run custom build

### ISSUE THREAD

**Issue by Annuther** [phonegap/phonegap-app-developer#418]
Hi,
Im using Win 8.1 and attempting the custom build targeting android  - ive only added one custom plugin to the config.xml file, thus:
`<plugin name="cordova-plugin-app-version"  spec="~0.1.8"/>`

 And changed the app id, reverse domain to my own in the config.xml  widget node (as advised).
I've tried using the run command without specifying the platform and also tried by specifying it both versions fail and im not understanding the npm log reasons - ive attached the log file if anyone could elaborate

cheers ...
![npm_err_log](https://cloud.githubusercontent.com/assets/18668429/14837289/ea6477d2-0c0e-11e6-8be6-4dd568845a72.png)

**Comment by timkim** [comment]
Hi @Annuther 

I would recommend just using the `cordova build ios|android` instead of using our run scripts. The run scripts are mainly for the PhoneGap's team way of producing a dev/prod build.

**Comment by Annuther** [comment]
@timkim,

Hi tim, tried that and i get a little further but now getting error readout before fail :
```

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v13:23+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v13/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v13/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-gcm:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-gcm/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 12.375 secs
Error: cmd: Command failed with exit code 1
```


Tell me should i remove the GIT repository specific files from the original cloned repo?? Those files and directories are not required for a custom build,no? what should be in the, `phonegap-app-developer` directory before compiling??

cheers ...

**Comment by timkim** [comment]
Hi again @Annuther 

It looks like you need some libraries to build Android. Update your sdks by:
```
$ android
```
And then make sure you have these libs installed:
Android Support Library
Android Support Repository
Google Play Services

You shouldn't have to mess around with the file structure of the repo. I'm pretty sure you're just missing some Android dependencies.

**Comment by macdonst** [comment]
@Annuther as what @timkim said above, you will need the libraries listed at:

https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/INSTALLATION.md#compilation

**Comment by Annuther** [comment]
@Annuther & @timkim,

Its working!! built and run without problems - also downloaded the Intel x86 emulator accelerator HAXM Installer as it was mentioned in the error message earlier - so i can create a fast emulator instance in the AVD alongside building to devices.

Thanks for the help much appreciated.

**Comment by timkim** [comment]
No problem @Annuther. Glad to hear you got it working.
