### ISSUE TITLE
Unable to compile/run: clang linker

### ISSUE THREAD

**Issue by tylercasey** [phonegap/phonegap-app-developer#419]
Unable to npm run phonegap -- run ios without getting clang errors on a clean git clone.  A reduced version of the output is below, running on a Macbook with i386.

Ld build/emulator/PhoneGap.app/PhoneGap normal i386

Undefined symbols for architecture i386:
  "_sqlite3_bind_blob", referenced from:
      ___59-[GMRSqliteStore upsertStatementForRecord:inTableWithName:]_block_invoke350 in libGGLCore.a(GMRSqliteStore.o)
      -[GCMRmq2PersistentStore saveMessageWithRmqId:tag:data:error:] in libGcmLib.a(GCMRmq2PersistentStore.o)

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

**Comment by macdonst** [comment]
@tylercasey couple of things to verify:

1. Make sure you are using Xcode 7 to build
2. Make sure you are using cordova-ios 4.1.x 
3. If the above two don't work try disabling bit code in xcode.

**Comment by tylercasey** [comment]
Xcode needed upgrade, build completes.  Thanks!
