### ISSUE TITLE
Include the Wizcorp facebook plugin

### ISSUE THREAD

**Issue by ZeroT** [phonegap/phonegap-app-developer#423]
Could the Wizcorp facebook plugin be included in the developer app, it would make testing on IOs devices a whole lot easier!  Very popular plugin too!

https://github.com/Wizcorp/phonegap-facebook-plugin

**Comment by surajpindoria** [comment]
Hi @ZeroT,

When we look into adding a plugin to the developer app we have to make sure that it supports all the platforms (Android, iOS, Windows). This plugin only has support for Android and iOS.

However if you would like to add this plugin yourself and create a build of the developer app with it included, please follow these [steps](https://github.com/phonegap/phonegap-app-developer#adding-custom-plugins).

**Comment by mwbrooks** [comment]
We definitely want to add popular plugins that help developers focus on building apps. If the plugin can be updated to _fail gracefully_ on Windows, then we could look at adding to the Dev App.

**Comment by purplecabbage** [comment]
for now you will need to build it yourself to get these functions.
