### ISSUE TITLE
Some app features not working under android 4

### ISSUE THREAD

**Issue by SamyDahmani** [phonegap/phonegap-app-developer#425]
Hello guys,

I have built an android app by using the phonegap builder, I'm just openning my website into the app.
Openning the website into a browser of android 4 is working fine.
My website is built in the backend with Django framework and with bootstrap 3.3.6 + Jquery + Ajax in the frontend.
# The issues:

The app is working fine in android 5 and 6
Some features are not working in android 4:
1/Searchbar not working:
-Choosing option from categories or groups dropdown is not returning any result.
-writing into text area is working but submit button is not working.
2/Autoload post when scrolling up:
-The posts are loaded at the top and one over the other instead of loading the to bottom. 

Do you have any idea about the root cause of my issues ?

Thank you.
Sam

**Comment by purplecabbage** [comment]
I suspect it is modern javascript which was not available in android 4, there weren't even promises.
Assuming this is answered, closing the issue.
