### ISSUE TITLE
phonegap desktop app stopped suddenly 

### ISSUE THREAD

**Issue by badrsh** [phonegap/phonegap-app-developer#431]
Hi , 
I Have problem withh my phonegap Desktop app 
the problem happen while i'm coding 

maybe every two or three minute or when i change something inside my project 

what i got is :
- the Desktop  app showing me black background on it and it didnt respond at all 
- the project stopped on the browser 
- i need to close the program and re open it again but I know that I  will got the error again

how can i fix this please ? ?

**Comment by timkim** [comment]
Hi @badrsh 

I think you actually want the https://github.com/phonegap/phonegap-app-desktop/issues issue tracker. This one is specifically for the PhoneGap Developer App.
