### ISSUE TITLE
Phonegap is incompatible with my SAMSUNG J2 AND J7 Model mobile phones in playstore

### ISSUE THREAD

**Issue by panalgin** [phonegap/phonegap-app-developer#432]
Hi, I have 3 phones, Sony Xperia ST26i, Samsung J200F and Samsung J700F.

İts compatible with such an old phone as Xperia ST26i, but incompatible with new phones. What is the reason? Thanks

**Comment by surajpindoria** [comment]
Unfortunately there isn't a whole lot we can do about device compatibility. Take a look at this related issue that offers a work around to downloading new versions of the app.

https://github.com/phonegap/phonegap-app-developer/issues/408

**Comment by johannmiller** [comment]
You can add Samsung Galaxy J3 to the list.
Android 5.1.1
HW Vers J32OP.02

Perhaps the solution is to offer a "phonegap core" app that's compatible with all Android phones running a particular version of the OS. Then let people install add-on's for various HW components. Basically make it more modular.

I'm not really sure how the workaround helps. I see a long list of apk's but still don't know which would work for my phone...

**Comment by chuckfossen** [comment]
I installed the latest apk and it worked on my J7 for at least the Hello World sample.

**Comment by purplecabbage** [comment]
You will need to build it yourself.  Please reopen if you have more to add to this issue.

**Comment by ColAstro** [comment]
Where can I find the apk for a J2? Or some instructions on how to build it? "You will need to build it yourself" isn't a huge amount of help.
