### ISSUE TITLE
iPhone6 Resolution scaled down?

### ISSUE THREAD

**Issue by wgpalexander** [phonegap/phonegap-app-developer#434]
Hi all,

I am using PhoneGap while I design & code an app.

When I launch the app on my phone it scales down the resolution to 375x667. I can't seem to find a definitive solution to this online.

I'm fairly new to scripting and PhoneGap so it could be something simple - a launch image issue perhaps?

Thanks
Wayne

**Comment by mwbrooks** [comment]
Hi @wgpalexander,

You will want to add or adjust your meta viewport tag.

- You can [learn more about the viewport](https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag) from Mozilla
- You can see examples in our [Hello World template](https://github.com/phonegap/phonegap-template-hello-world/blob/master/template_src/www/index.html#L28) and [Star Track app](https://github.com/phonegap/phonegap-app-star-track/blob/master/www/index.html#L18)
