### ISSUE TITLE
Question: same network

### ISSUE THREAD

**Issue by boustanihani** [phonegap/phonegap-app-developer#440]
Just wondering why the machine and the device should be on the same network for the PhoneGap App to work?? I am developing using a Cloud-IDE (https://c9.io/) which many users will be using... So my App and my server won't be on the same network... Any workarounds?

**Comment by surajpindoria** [comment]
Hi @boustanihani,

For the Developer App to work, we start up a local server on your machine that the mobile device can then connect to and download your apps assets.

Another method you could try is to create a zip with your `www` directory and expose that with a public URL. But this will not allow you to edit files and see the changes live in the app. Other than this there is no other way around using the same network.

**Comment by boustanihani** [comment]
Thanks for the info, but why can't the Developer App download the app assets from any server we choose?

**Comment by surajpindoria** [comment]
Actually I believe this may work. I have personally never tried it but as long as the server is publicly accessible I don't see why it wouldn't. The only issue may be with download speeds on the phones end.

**Comment by boustanihani** [comment]
I tried this but I am getting a network error and the FAQ also states the following:
"First, you should verify that your machine and device are on the same network." (Why is this so?)

Check: http://docs.phonegap.com/references/developer-app/troubleshoot-faq/

**Comment by timkim** [comment]
Hi @boustanihani 

While we do say that your machine and device should be on the same network, it is possible to serve on a public address. However, this requires additional setup on your side in that you'll need to set up your own server to serve the project to any device that will connect to it. 

If you're having trouble connecting up your own end point, it's probably because the server path needs to have a special route for the dev app to connect. For example, if we do the `phonegap serve` command, you'll see it'll start broadcasting like this: 
```
[phonegap] starting app server...
[phonegap] listening on 10.58.133.149:3000
```
So when you type that into the dev app, the actual request for the app zip is:  `10.58.133.149:3000/__api__/appzip`. 

So you'll have to setup your server so it can handle the `/__api__/appzip` end point.

**Comment by boustanihani** [comment]
I made some steps forward, the problem was with my URL (I am using a URL instead of an IP-Address), when I removed the slash at the end it worked. This is a bug because the Phonegap-Developer-App should check for a trailing slash before appending `/__api__/appzip` to the URL.

Now my app is being downloaded and extracted, but when it starts I only see a white screen, but if I open my app in a browser, all works fine...

Now I need to debug to see what's happening, but sadly I see no WebViews when I check `chrome://inspect/#devices`. I have USB debugging turned on and when I open Chrome on my smartphone I can inspect the tab using `chrome://inspect/#devices`. Any ideas?

**Comment by boustanihani** [comment]
I found out why "PhoneGap Developer app is a production version app" :)

But don't u think it would be nice if PhoneGap offers a "developer version app" which could be downloaded from the PhoneGap site? I know we can do a custom build I just find this handy so one can directly test USB debugging without additional steps...

**Comment by timkim** [comment]
Hi @boustanihani 

Sorry about the long response time, I got caught up with some other work. 

Ya, not having USB debugging with the production version of the app is definitely a bummer. We're still working on possibly having it one day in some form. 

As for having a developer version of the app available for download, I feel like it's more worthwhile to have users build their own version of the app if they so wish. 

Are you still having trouble with trying to use your own server to serve assets?

**Comment by boustanihani** [comment]
Sorry for the late reply, I am no longer having  trouble trying to use my own server to serve assets.

And as you said, not having USB debugging with the production version of the app is definitely a bummer, are there any updates on this?

**Comment by surajpindoria** [comment]
Glad to hear you are not seeing this issue anymore. Also, I am responded to your question on another issue that you commented on. https://github.com/phonegap/phonegap-app-developer/issues/49#issuecomment-299940620

Going to close this off now.
