### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-app-developer#441]
@wadie commented on [Sun Aug 28 2016](https://github.com/phonegap/app/issues/5)

Hi,

I have a Samsung Galaxy J7 and as it appears to be on Google Play Store, is that the phonegap app can't be installed on my device. simply not compatible.

Any input on this ?

**Comment by surajpindoria** [comment]
Thanks for moving this over @shazron,

This is a common problem we have seen recently. Unfortunately there isn't really a proper solution around this. Some users have found workarounds to install the app which work, but we cannot guarantee that all the features will work. @wadie, you can take a look at this issue for reference on how people have worked around this.

https://github.com/phonegap/phonegap-app-developer/issues/408

**Comment by hbroer** [comment]
Same Problem here:
Huawei GR3, fresh installation, no sim card, Android 5.1, EMUI 3.1 Lite, Kernel 3.10.65
My (lost) Sony Z1 Compact is still listed as compatible

**Comment by wadie** [comment]
Check this
https://github.com/phonegap/phonegap-app-developer/tree/master/resources/release

**Comment by purplecabbage** [comment]
You will need to build the app your self for these android target.

**Comment by raymondvangelder** [comment]
I have the same problem on a Motorola g5 + with Android 8.1.0
