### ISSUE TITLE
err_file_not_found

### ISSUE THREAD

**Issue by aluferraz** [phonegap/phonegap-app-developer#443]
Hi,

Whenever I try to load a resource from the root directory, I get a error (net::ERR_FILE_NOT_FOUND). For exemple:

  `<script src="/js/indexjs"></script>`

GET file:///js/index.js net::ERR_FILE_NOT_FOUND

But, if I load the file without the first slash, it loads just fine:

`<script src="js/indexjs"></script>`
GET file://js/index.js 

It seems that phonegap doesn't understand that the first slash means the root folder..

**Comment by surajpindoria** [comment]
Hey @aluferraz,

I believe the second method is the correct way to load resources from your project. When your app is running it is already using the project directory as the current, so all paths should be relative to this.

**Comment by aluferraz** [comment]
Hi @surajpindoria,

Maybe I've misunderstood the feature..So, with phonegap I can only have relative paths  (like ../)? I have a angular 2 app and  every assets of mine is placed at the root folder, so in all components I've tried to load my assets by placing "/assets/img1.jpg", which work just fine with web browsers...

Do I have to change it to relative paths to load the assets with phonegap ? Like this  "../../../../assets/img1.jpg"  ?

**Comment by surajpindoria** [comment]
Yes that is correct.

One thing you could consider that may help out is to add a helper function that will find the project root. This way you don't need to go through and manually add all the `../../`... to your paths.

**Comment by aluferraz** [comment]
Excellent! Thank you  !!!
