### ISSUE TITLE
IOS sjcl is too slow

### ISSUE THREAD

**Issue by Nargott** [phonegap/phonegap-app-developer#444]
Hello. I'm recognized, that in Android **sjcl** crypto works fine and fast.
But in IOS even if I'm running my app by "phonegap serve" in Cordova browser, it was has a long time for doing crypto work (about 30s). 
sjcl.misc.scrypt function is working about only 1-2s in Android, but in IOS in tooks about 30-35s!
Why is it happen?

**Comment by purplecabbage** [comment]
Please post an example that demonstrates your issue.  Preferably as simple as possible.

**Comment by devgeeks** [comment]
The problem comes down to a lack of a JIT like Nitro in the default web view on iOS. 

In order to use sjcl on an iOS PhoneGap app, you'll need to look into using the WKWebView. 

This means you won't really be able to use the developer app :(
