### ISSUE TITLE
Repository too large to clone

### ISSUE THREAD

**Issue by marciot** [phonegap/phonegap-app-developer#449]
Every release of the phonegap-app is included in resources/release folder. This makes this repository gigantic and a major problem to clone. It also makes it impossible to clone this repo directly into PhoneGap Build so that I can add a new plugin (this is because PhoneGap Build has a 50MB limit on clones).

I would make the recommendation that this repository is cleaned out so it just contains the source code and not the releases. The only way to do this might be to nuke the repo and start again, alas.

**Comment by shazron** [comment]
Related: https://github.com/phonegap/phonegap-app-desktop/issues/687

**Comment by marciot** [comment]
Thanks for the fix suggestions, Shazron.

**Comment by timkim** [comment]
Hi @marciot 

Ya, we'll be moving away from putting the binaries into the `resources/`. In the mean time, the above link provided by @shazron will have to do.

**Comment by marciot** [comment]
It appears as if GitHub lets you attach binaries to releases:

https://help.github.com/articles/about-releases/

It's not 100% clear, but I think releases are not cloned with the main repository and thus are ideal for what you are needing to do.

**Comment by timkim** [comment]
Oh! Well how about that. Looks like we'll just that!

Ya, I'm getting the feeling that releases aren't cloned since you seem to link to them individually.

**Comment by shazron** [comment]
Don't forget just erasing the releases from the repo won't reduce the size, you have to remove them from the history as well (see the link to the other issue I posted on how to remove).

**Comment by purplecabbage** [comment]
This also may be a case where a git submodule actually makes sense.
