### ISSUE TITLE
PhoneGap iOS build weird behaviour

### ISSUE THREAD

**Issue by braj008** [phonegap/phonegap-app-developer#476]
My phonegap iOS build works fine if I run it through PhoneGap desktop and mobile apps but not working if ran independently (through xCode).

One more weird issue is that, it works fine again if I do the following:

- Open independent build in device and press home button
- Open PhoneGap developer app and run your app and press home button
- Now, open independent app and it works just fine

Could not understand this crazy behaviour. This is not the case with Android build though.

Any help or clue is greatly appreciated.

**Comment by surajpindoria** [comment]
Hi @braj008,

So what is the issue that you are seeing on iOS? It is just not loading when you attempt to launch from xcode? Are you launching `<project-dir>/plaforms/ios/*.xcodeproj` to open in xcode?

**Comment by braj008** [comment]
Hi @surajpindoria,

Thank you for the response. It was a Content-Security-Policy issue which I was able to fix with following line to my index.html file.

`<meta http-equiv="Content-Security-Policy" content="default-src 'self' * gap://ready; style-src 'self' 'unsafe-inline' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *">`

**Comment by surajpindoria** [comment]
Glad to hear you got it figured out!
