### ISSUE TITLE
fail on add  plugin : cordova-plugin-fcm

### ISSUE THREAD

**Issue by ricardojlrufino** [phonegap/phonegap-app-developer#479]
I'm having trouble adding the plugin: cordova-plugin-fcm.

I removed the old plugin 'phonegap-plugin-push' and cleaned 'phonegap clean'.

To compile you must change the file: platforms/android/build.gradle
```
// Change to version: 1.2.3+
classpath 'com.android.tools.build:gradle:1.2.3+'
```
ref:https://github.com/fechanique/cordova-plugin-fcm/issues/6

Then installed and gives the following error in the adb log:

> E/AndroidRuntime(29924): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/br.com.criativasoft.mobile.edu3-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime(29924): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(29924): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(29924): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(29924): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5072)
E/AndroidRuntime(29924): 	... 11 more
E/AndroidRuntime(29924): 	Suppressed: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(29924): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(29924): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(29924): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(29924): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(29924): 		... 13 more
E/AndroidRuntime(29924): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

NOTE: This error only appears when I add the plugin

phonegap --version              
6.3.3

**Comment by surajpindoria** [comment]
Hi @ricardojlrufino,

I have run into a similar error like this before. Have you updated all of your Android SDKs and APIs to the latest version? If not can you try updating those and then reinstalling the plugin.

**Comment by purplecabbage** [comment]
assumed answered.  please reopen if you are still having an issue.
