### ISSUE TITLE
Phaser game engine

### ISSUE THREAD

**Issue by qroft** [phonegap/phonegap-app-developer#483]
I am trying to use the phaser.io game engine together with the desktop app.
I am developing with brackets and there the LIVE preview works perfectly within my Chrome browser.
So i started the Phonegap App on my Samsung Galaxy to see if i could do "live mobile testing".
But the changes do not take effect.

Has anyone ever tried out if any one of those html5 game engines work with the phonegap desktop app?

**Comment by purplecabbage** [comment]
Phaser should work fine with the developer app, be sure that you do no have some extra build process or something that is modifying files outside the www/ folder. That is the only thing I can think of ...
Are you still having this issue?
