### ISSUE TITLE
Need for a CACHED option

### ISSUE THREAD

**Issue by BenGermany** [phonegap/phonegap-app-developer#489]
It's annoying there is no caching option in the developer app on Android and iOS. Every time I am away from home the app can't connect to the service on my PC an deletes(!) my actual App. Can you implement a button for a cached (the last loaded app) at startscreen? This should be pretty simple - a CACHED button and a RESET ALL option would be pretty nice! The reset button would be nice and generally needed, too.

Thank you very much :-)

**Comment by timkim** [comment]
Hi @BenGermany 

In the next version of this app, I believe we are planning on adding this feature. However, we're not sure when exactly that will be but I'm guessing sometime in Fall or Winter of this year.
