### ISSUE TITLE
PhoneGap Build Service

### ISSUE THREAD

**Issue by mbinette** [phonegap/phonegap-app-developer#493]
I'm trying to use build.phonegap.com to create a custom phonegap-app-developer application with a couple plugins that I need in my project. As is mentioned hundreds of times in the issues, I clone this repo, run the build in build.phonegap.com and get a successful build. But when run on my Android 6 or iOS 10 devices I get the "Downloading..." flashing and it never makes it past that.

The standard phonegap-app-developer app installed through the app store works perfectly fine with my PhoneGap v0.4.4 desktop server. I would think a clone, no changes, build, should also work but doesn't.

I only have a Windows machine so can't do the builds locally. Is this something a developer on this project can test and fix or is it something the PhoneGap Build folks need to work on? And if PhoneGap Build folks, does anyone have a suggestion as to the best place to make the request?

Rebuilding my app and re-installing on my devices for each change is getting very tiring.

**Comment by timkim** [comment]
Hi @mbinette 

This project isn't very PhoneGap Build friendly. There are some scripts that are run at build time to help inject some stuff that we need. It is possible that when you upload the project to PhoneGap Build that some of that stuff goes missing and leads to a JS error. Without knowing the debug logs when you try to download something, I can't say for certain what is exactly going wrong. 

And without doing the builds locally, I'm not sure if you can get around these problems. I could try making a branch that is nicer for PhoneGap Build. However, if you can build locally I would suggest you try this: http://docs.phonegap.com/references/developer-app/custom-build/ios/
