### ISSUE TITLE
push notifications: tutorial and developer guides are inconsistent

### ISSUE THREAD

**Issue by ben-henoida** [phonegap/phonegap-app-developer#494]
The tutorial and developer guide are inconsistent :  http://docs.phonegap.com/tutorials/develop/push-notifications/ VS
 http://docs.phonegap.com/develop/push-notifications/ 
Eg: "Sending Your First Push" differentiates between windows and 'MacOs' and uses fcm instead of gcm for android.

**Comment by surajpindoria** [comment]
Hi @ben-henoida,

Thanks for pointing this out, I will take care of this!

**Comment by macdonst** [comment]
@ben-henoida please use http://docs.phonegap.com/tutorials/develop/push-notifications/

The two links you posted above should both lead to the same page. We are looking into it.

**Comment by macdonst** [comment]
@ben-henoida we've deleted the old docs at http://docs.phonegap.com/develop/push-notifications/ and it 404's now.
