### ISSUE TITLE
phonegap gestures not working

### ISSUE THREAD

**Issue by gms384** [phonegap/phonegap-app-developer#495]
Phonegap gestures (http://docs.phonegap.com/references/developer-app/gestures/) are not working for me in a project with MULTIPLE HTML pages.  In this case:

- the gestures work fine from index.html
- they work fine from other .html pages at the same level as index.html
- they do not work from .htm pages within my project (even when I include cordova.js in those pages)
- they do not work from .html pages that are within subfolders of my project (even when I include cordova.js in those pages)

I am using PhoneGap Build 0.4.5 with cli-c.5.0 on iOS 9.3.5.
 
Any ideas? I can of course force-quit the app and reload but that gets tedious very quickly.

FWIW:  Navigation between pages is working fine.  The only part broken is the gestures.

**Comment by surajpindoria** [comment]
Hi @gms384,

Not sure what could be causing this as the scripts that we inject for gestures should work from any HTML page. Usually when we find issues with the gestures it is the result of the some broken JS that is causing errors on the page. Maybe it could be an issue with the specific pages you are noticing this on.

Another thing to check, we attach the gestures to using event listeners. So if you have something on your site that effects those that could cause the issue as well.

**Comment by gms384** [comment]
Thanks for the quick response.  I do not think that is the issue though.  To test, I did this:

1. created blank Phonegap project
2. edited index.html to add this:

        <a href="index.html">index</a>
        <a href="good.html">good</a>
        <a href="bad.htm">bad</a>

saved resulting file as index.html, then as good.html, then as bad.htm.

when you navigate to index.html- gestures work.

when you navigate to good.html- 3-finger tap does "back" to index.html then 3-finger does back to reload- all good.

when you navigate to bad.htm - 3 finger tap does not work at all.

code in all 3 pages is the same (ie default index.html page with these 3 links)

You can achieve similar result by putting index.html page within a subfolder (and adjusting the path to cordova to be correct:  <script type="text/javascript" src="../cordova.js"></script>)

Greg

**Comment by surajpindoria** [comment]
Well the quick fix would be to rename bad.htm -> bad.html. In `connect-phonegap`, where we inject all these scripts, we are specifically looking for html files.

**Comment by gms384** [comment]
True- but I am dealing with a project with 50-100 html files, and would even consider renaming them from .htm to .html, but they exist in a folder structure which I cannot feasibly flatten.  Is there hope that at some point you can inject your scripts into all the htm/html files within the project?

**Comment by gms384** [comment]
One other quick fix that might help would be a simpler way to quit the application rather than force-quit. I've tried both navigator.app.exitApp() and setting exit-on-suspend as listed in http://docs.phonegap.com/phonegap-build/configuring/preferences/#exit-on-suspend but neither worked.

Is there a way to simpler call to quit the app?  I realize that you don't want to do that for production, but it sure would be helpful during development.

**Comment by surajpindoria** [comment]
Because we are loading your project resources into the developer app there isn't really a good catchall that would quit the app back to the home screen. This is why we need to inject these scripts into your served application so that we can provide this functionality. But all the 3 finger tap is doing is calling `window.history.back(window.history.length);`. So for now on the broken pages you are seeing you can add this as a way to go back a page.

**Comment by timkim** [comment]
Hi @gms384 

I made a quick fix to the server side component [connect-phonegap](https://github.com/phonegap/connect-phonegap) to allow the scripts to be injected into .htm files. We're currently adding some more things to the phonegap-cli so the update should be ready in a few days time.

**Comment by gms384** [comment]
Thanks- that's awesome!  Will it also handle .htm files in subfolders?  That is the bigger problem.

**Comment by surajpindoria** [comment]
I have just release phonegap-cli@7.0.0 that has the changes needed to fix your issue @gms384. Thanks for bringing this to our attention!

**Comment by gms384** [comment]
That's great...thanks!  Maybe a dumb question:  I am using PhoneGap Desktop application.  Is there a way to update the cli to your new release, or would I have to abandon the desktop version and use the command line version until the next PhoneGap Desktop release?

Or do you mean that http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/#win is updated as well?

Thanks again,
Greg

**Comment by surajpindoria** [comment]
The PhoneGap Desktop app has not been updated yet, for this fix you will need to use the phonegap-cli. Once you have the CLI installed you just need to run `phonegap serve` and it will do the same thing as the desktop app.

**Comment by gms384** [comment]
Sorry for more questions- I am new to this.  I assume to install it is just:

npm install -g phonegap-cli@7.0.0 

If I do that, will it affect in any way my version of PhoneGap build, or will I still be able to use either PhoneGap build (as it currently is) or the newer fixed CLI version?

If there is some interaction, does it make any sense to install it with:

npm install phonegap-cli@7.0.0 

and would that change anything?

thanks,
Greg

**Comment by surajpindoria** [comment]
Yes, that is the correct way to install the CLI.

I think you have the names a little confused but either way installing the CLI will not affect anything else you have installed. The desktop app comes bundled with its own version of the CLI and currently it does not have the fix for your issue. PhoneGap build is different, that is a website where you can upload your project assets to create a build.

**Comment by gms384** [comment]
Thanks for clarifying names- and yes I meant the desktop app.  I went to install the CLI with:

npm install -g phonegap-cli@7.0.0

and it says:

'phonegap-cli' is not in the npm registr
You should bug the author to publish it

Am I doing something wrong?

**Comment by surajpindoria** [comment]
Sorry, I didn't notice you had added the "-cli" at the end. It should just be, `npm install -g phonegap`.
