### ISSUE TITLE
Upload ipa using Application loader

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-app-developer#497]
We getting the following error.please advice
##  no .app bundles found in the package

**Comment by timkim** [comment]
Hi @edvenkat 

Can you explain more what you are trying to do? Are you trying to build this app and then upload it to the App Store?

**Comment by edvenkat** [comment]
I created the IPA using phonegap build and link to production certificate and distribution provision profile

Using application loader from Xcode beta version upload IPA to iTunes connect the application loader show the above error

**Comment by timkim** [comment]
After some digging it looks like you may have to upgrade your xcode version out of beta for it to work. So use Xcode 8.x. 

Source: https://stackoverflow.com/questions/37838487/error-itms-90167-no-app-bundles-found-in-the-package
