### ISSUE TITLE
Ionic v1 angularJS, How to display a value based on max and min from a json array

### ISSUE THREAD

**Issue by coolbeatz71** [phonegap/phonegap-app-developer#498]
Hello, everyone, im developing a mobile banking application using ioniv v1. I hav a form for making a withdraw.I want when the user enter any amount, it display automaticaly in the html view, the cost for this amount.

my json object look like this: 

$scope.rateWithdraw = [
		{min: 0.10, max: 5, transtype: 'WITHDRAW', value: 0.60, currency: 'USD', comment: 'class1'},
		{min: 5.01, max: 10, transtype: 'WITHDRAW', value: 0.65, currency: 'USD', comment: 'class2'},
		{min: 10.01, max: 20, transtype: 'WITHDRAW', value: 0.70, currency: 'USD', comment: 'class3'},
		{min: 20.01, max: 50, transtype: 'WITHDRAW', value: 0.75, currency: 'USD', comment: 'class4'},
		{min: 50.01, max:  100, transtype: 'WITHDRAW', value: 1.25, currency: 'USD', comment: 'class5'},
		{min: 100.01, max: 200, transtype: 'WITHDRAW', value: 2, currency: 'USD', comment: 'class6'},
		{min: 200.01, max: 300, transtype: 'WITHDRAW', value: 3, currency: 'USD', comment: 'class7'},
		{min: 300.01, max: 400, transtype: 'WITHDRAW', value: 4, currency: 'USD', comment: 'class8'},
		{min: 400.01, max: 1000, transtype: 'WITHDRAW', value: 5, currency: 'USD', comment: 'class9'}
	];

Example, if the user type in the form an amount which is equal to 24$, the application must located in which interval, the amount is located (In occurence min: 20.01, max: 50) and display the cost for it (in occurence, value: 0.75$). Help me please, because im a beginer in ionic and angularJS

**Comment by timkim** [comment]
Hello @coolbeatz71 

This isn't really the place to be asking JS questions like these. You're better off asking in a place like [stackoverflow](https://stackoverflow.com/questions/tagged/javascript).

But since you asked, you need to use a for-loop to iterate over your JSON objects in the array and figure out what the appropriate object is.
