### ISSUE TITLE
Retina image

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-app-developer#503]
I have implemented the retina concept in my mobile app
The image get from the local or image folder
But the App size same for all device (Iphone 5s, iphone 6, etc)
do we need to add the any settings in config.xml files
Please advice.

**Comment by timkim** [comment]
Hi @edvenkat 

I'm a little confused. Are you saying that the retina image sizes are not in the proper resolution when you preview them in the developer app?

**Comment by edvenkat** [comment]
No @timkim 

Retina replace the image by following ways
1. 2x image for iphone5s
2. 3x image for iphone 6 or 6s
is correct??
We think, While generating ipa file

For iphone 5s , it will not include 3x image
For iphone 6 or 6s, it will not include 2x image

if so, the ipa file size should be different for iphone 5 and iphone 6 or 6s.. it is not happen

Why?? please correct me if my understanding is wrong

**Comment by purplecabbage** [comment]
It is very difficult to debug issues like this.  I would recommend that you create images of each size/name that are extremely obvious ie. all red for 2x and all green for 3x and verify that the right ( or wrong ) images are loaded in each case.
If you still cannot resolve this still, please reopen and point us to a simple sample that reproduces the issue.
