### ISSUE TITLE
Closing a browser(chrome) makes the App to restart

### ISSUE THREAD

**Issue by laraprabhu** [phonegap/phonegap-app-developer#504]
Phonegap app is getting restarted in certain scenarios,

**_Working scenario:_**

>  Open app -> Press home button -> Open app -> App resumed.

**_Problematic scenario:_**

> Open browser -> Press home button -> Open app -> Close browser (swipe it out) -> Return to the app, now we can see the app restarts.

**_Version details:_**

I am seeing this behavior in Android V 7.0. Haven't got a chance to test it in others. And the command `phonegap -v` has yielded me `7.0.0`. Running the app in `Lenova Z2 Plus`.

**_Attempts:_**

I have used the following preferences in `config.xml`.

`<preference name="AndroidLaunchMode" value="singleTask"/>`

as well as

`<preference name="AndroidLaunchMode" value="singleTop"/>`

But nothing helps.

**_Additional notes:_**

Tested the same behavior with a most popular phonegap app TripCase. It is also behaving in same manner.

Is this a known behavior? If yes, Do we have a workaround for this? I mean, Is there a way to stop the app restarts when closing a browser (chrome)?

**Comment by surajpindoria** [comment]
Hey @laraprabhu,

Is this happening when you are previewing your project in the developer app? Or is this on a compiled version that you have installed on a device?

**Comment by purplecabbage** [comment]
Please provide more details and re-open if this is still an issue.  We cannot recreate it with the info given, but it sounds like this is just the way things are in cordova-android.
