### ISSUE TITLE
No scroll inertia/momentum 

### ISSUE THREAD

**Issue by edvenkat** [phonegap/phonegap-app-developer#505]
Hai All,

No scroll inertia/momentum - when i scroll the page, the event scroll call only end of the scroll not between

please advice

```
$$('#xxx').scroll(function () {
}); 
```

**Comment by edvenkat** [comment]
I have added the code in below url

https://github.com/edvenkat/sticky-header


Please advice.

**Comment by timkim** [comment]
Please seek the answer to these kind of questions on stackoverflow or https://forums.adobe.com/community/phonegap. This repo is for issues concerning the PhoneGap Developer App and not for javascript on mobile.
