### ISSUE TITLE
Unable to download archive on android

### ISSUE THREAD

**Issue by msolovyov** [phonegap/phonegap-app-developer#507]
Getting a 404 http://IPADDRESS:3000/__api__/appzip on the desktop app logs. Also same with phonegap serve cli. 

All latest versions:
Developer app 1.7.1 and 1.7.2
Desktop app (OSX) 0.4.5
phonegap cli 7.0.1

I can go to  http://IPADDRESS:3000 on the browser on the phone and view my app. I can also go to http://IPADDRESS:3000/__api__/appzip on the browser on the phone and download the zip fine. 

One thing I noticed is when I download the zip through browser in the logs I see a 202 /__api__/appzip whereas the 404 has the ipaddress in it.

**Comment by surajpindoria** [comment]
Hi @msolovyov,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by msolovyov** [comment]
@surajpindoria thanks but none of the suggestions apply in this case because I can download the zip file just fine from the phones browser but not through the developer app. Thus it is not a network issue but an app issue.

**Comment by timkim** [comment]
@msolovyov what phone are you using and what version of its os?

**Comment by msolovyov** [comment]
Sony Xperia z5 compact. Android version 7.0

**Comment by msolovyov** [comment]
Seems to be fixed now. Only major change I did is: 'phonegap platform rm android' 'phonegap platform add android' 

But it could have been something else. Closing for now until it returns.
