### ISSUE TITLE
No style for latest update

### ISSUE THREAD

**Issue by jesobreira** [phonegap/phonegap-app-developer#508]
The app got updated on Apple Store 5 minutes ago and now it shows a style-less page.

Also the topbar coloring isn't working anymore.

Tried uninstalling and reinstalling but no luck.

Tested on iOS 11, iPhone 7.

![captura de tela 2017-10-01 as 18 22 22](https://user-images.githubusercontent.com/3002249/31059111-8215e86a-a6d5-11e7-9501-d7f43d166dd5.png)

**Comment by timkim** [comment]
Hi @jesobreira 

An update has been submitted to the app store regarding this bug and a fix new release should be out shortly.

**Comment by jesobreira** [comment]
Now, since last night, it says that this app is not available on the Brazilian store (I am from Brazil) and I am unable to update the app (truly, if I delete it, I will not be able to install it again).

**Comment by surajpindoria** [comment]
Since the current build is broken we have taken it off of the app store while the new version is being approved by Apple. It should be back up in a few days. @jesobreira

**Comment by timkim** [comment]
Hi @jesobreira 

The app is back in the stores now. Sorry about that!
