### ISSUE TITLE
Displaying the value of alt tag instead of image- Is this bug?

### ISSUE THREAD

**Issue by damithruwan1234** [phonegap/phonegap-app-developer#509]
Lets see following code.

`$("#image_area").html('<img class="img-responsive" src="images//2000.jpg" alt="Test">');`

**This work fine with the browser**. That means image is displayed inside "image_area" div.

But in device it displayed just "Test". It means in the device it display the value of ALT tag instead of image when we use jquery ..html function.

Is it a bug? How I solve it?

**Comment by purplecabbage** [comment]
You appear to have a issue with the path to the image.  The browser may be more forgiving, or the asset might not be part of what is copied to the device.
images//2000.jpg <= could it be as simple as 2 slashes?  Please reopen if you still cannot resolve this.
