### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jayfagin** [phonegap/phonegap-app-developer#515]
Loaded the newest Phonegap developer app for windows. Version 0.4.5.  Modified the index.html file from the hello world project.  inserted a simple form with an input box and submit button.  Using iphone 5se IOS 10.3.3 loaded the page.  The submit button does nothing.  Tried 20 different ideas from various forums.  Whitelist plugin, CSP changes and access wide open changes.  Nothing worked.  Installed from scratch on another developers windows system with same result.  Loaded on a mac and it worked perfectly.

**Comment by timkim** [comment]
Hi @jayfagin 

You are talking about using the PhoneGap Desktop App, yes?

**Comment by jayfagin** [comment]
Yes, PhoneGap version 0.4.5.  on my MS Windows Surface Pro 3 Windows 8.1.  Running html page on Iphone 5se IOS 10.3.3  

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by timkim** [comment]
Hi @jayfagin 

You probably have firewall issues. See this doc to help you resolve the issue: http://docs.phonegap.com/references/developer-app/troubleshoot-faq/#phonegap-developer-app-is-unable-to-download-from-the-server

Specifically, try pinging your phone's ip to see that your Surface and can even find your phone on the network. If you can't get the ping to resolve, make sure the firewall allows NodeJs like so:

1. On Windows, open your Settings or Control Panel
2. Find the Windows Firewall settings
3. Find the Allowed Apps section
4. If NodeJS is listed
5. Allow NodeJS network access
6. If NodeJS is not listed
7. Select Allow another app
8. Locate NodeJS on your system

**Comment by jayfagin** [comment]
There must be some misunderstanding.  Phonegap Version 0.4.5 is running fine on my Windows 8.1 Surfacepro.  The index.html does load on my iphone 5se IOS 10.3.3.  DeviceReady and icon appear on my iphone.  When I make any change to the index.html in the www folder it is immediately loaded onto the iphone and all changes appear correctly.  I can ping my iphone from my surfacepro.  

 

However, when I load an index.html with a simple <form action=gosomeplace.com (or any page)>  the Submit button will not work.  Nothing happens.  No errors, just nothing.

 

I have sent my entire setup to a fellow who has Windows 7 and the same version of Phonegap and the same IOS version 10.3.3 on his iphone.  It worked for him without an issue.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by jayfagin** [comment]
That being said.  I did follow the instructions and loaded the NodeJS application.  It did not resolve the Submit button issue.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

 

 

From: Jay Fagin [mailto:jay.fagin@foxrunsolutions.com] 
Sent: Thursday, November 30, 2017 1:38 PM
To: 'phonegap/phonegap-app-developer' <reply@reply.github.com>; 'phonegap/phonegap-app-developer' <phonegap-app-developer@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [phonegap/phonegap-app-developer] Windows (#515)

 

There must be some misunderstanding.  Phonegap Version 0.4.5 is running fine on my Windows 8.1 Surfacepro.  The index.html does load on my iphone 5se IOS 10.3.3.  DeviceReady and icon appear on my iphone.  When I make any change to the index.html in the www folder it is immediately loaded onto the iphone and all changes appear correctly.  I can ping my iphone from my surfacepro.  

 

However, when I load an index.html with a simple <form action=gosomeplace.com (or any page)>  the Submit button will not work.  Nothing happens.  No errors, just nothing.

 

I have sent my entire setup to a fellow who has Windows 7 and the same version of Phonegap and the same IOS version 10.3.3 on his iphone.  It worked for him without an issue.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by purplecabbage** [comment]
I assume the submit button is not touch enabled, or something.
Without steps to reproduce this issue we cannot fix it.
Please reopen and post a simple sample if you would like us to look at it.

**Comment by jayfagin** [comment]
This worked on another iphone with Phonegap running on a Windows 7 computer.  The only difference is the version of windows.

 

Thanks,

 

Jay Fagin

President
FOX RUN Systems & Solutions
513.238.0083   |    <http://www.foxrunsolutions.com/> foxrunsolutions.com

 



 

 

 

Confidentiality Notice: This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
