### ISSUE TITLE
Windows custom plugin with Java

### ISSUE THREAD

**Issue by jayakrishna-v** [phonegap/phonegap-app-developer#517]
Hi Team,

I am creating a new Phonegap application for windows. I have a third party SDK in the form of .jar file. 
According to the Windows custom plugin development documentation, we can create custom plugins by creating run-time components in C++ or C#/VB.

But Is it possible to create a custom plugin to access the .jar file? i.e., can we create a custom plugin using Java?

**Comment by surajpindoria** [comment]
Unfortunately this is not possible as Cordova/PhoneGap only supports Windows Universal apps, and they do not support Java files. Below is a link for all the languages that are supported though.

https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide#writing-code
