### ISSUE TITLE
still the same Problem with "Content Security Policy"

### ISSUE THREAD

**Issue by Marix1** [phonegap/phonegap-app-developer#519]
today the is still the same Problem on Projects that worked last year.

We use Desktop App 0.4.5 and latest Android App 1.8.4

Now everytime this error:

undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

**Comment by surajpindoria** [comment]
Hi @Marix1,

This is not actually an issue but the intended behavior. In order for the desktop app to serve your application to the PhoneGap Developer app, we need to add/modify to your existing CSP.

**Comment by purplecabbage** [comment]
please reopen if this is still an issue.
