### ISSUE TITLE
In wich directory install?

### ISSUE THREAD

**Issue by Jomme5** [phonegap/phonegap-app-developer#520]
In wich directory do you have to execute this command? 
$ git clone https://github.com/phonegap/phonegap-app-developer.git
Is it a temp. dir/cordova app-dir or what?
Thx.

**Comment by surajpindoria** [comment]
Hi @Jomme5,

You can clone this repo to any directory you want on your computer. Is there something in particular you are trying to accomplish?

**Comment by Jomme5** [comment]
Ok, I got it installed.
