### ISSUE TITLE
Got stuck on 'downloading'

### ISSUE THREAD

**Issue by Jomme5** [phonegap/phonegap-app-developer#521]
Compiled the app successfully but got stuck on 'downloading.' I can access the server from the web-browser. Ip-address and port are correct.

**Comment by surajpindoria** [comment]
Hi @Jomme5,

Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by Jomme5** [comment]
Here is when I got the download-hang. The version number on the app was %PHONEGAP_APP_VERSION%
Looking in chromed-dev-tools I saw a certain js-libs weren't loaded. 
`$ npm run phonegap -- run android`

Solution(for me) was a build and copying and install the apk to the device.
`$ npm run phonegap -- build`

**Comment by Centipede5** [comment]
Hey if anyone still has this issue and doesnt want to change their firewall try using ngrok (https://ngrok.com/) and then run ngrok http 3000 and put that address in
