### ISSUE TITLE
Trying to directly run the custom build produces a broken package

### ISSUE THREAD

**Issue by pzanitti** [phonegap/phonegap-app-developer#523]
Note: I only tried this with Android, but seems the same for all platforms.

If you run with `npm run phonegap -- run android` it never connects, it gets stuck at `DOWNLOADING...`. It fails because of this function:

```
Uncaught TypeError: Cannot read property 'trim' of undefined
    at getVersion (analytic.js:83)
    at Object.window.phonegap.app.analytic.basicGELF (analytic.js:65)
    at window.onerror (app.js:77)
```

https://github.com/phonegap/phonegap-app-developer/blob/83417c7fb083ebc2ec7df8441806ad444866e0d8/www/js/analytic.js#L82-L84

Since `npm run phonegap -- run <version>` does not replace the `%PHONEGAP_APP_VERSION%` placeholder in `index.html`, the `trim()` call fails.

What works however is `npm run phonegap -- build android` and installing the generated .apk with adb, since it does replace `%PHONEGAP_APP_VERSION%` to `YOUR.WIDGET.ID : 1.8.4`.

**Comment by timkim** [comment]
Hi @pzanitti 

I've committed a fix - try giving it a go now.

**Comment by pzanitti** [comment]
Fixed.
