### ISSUE TITLE
Esta app no es compatible con tu dispositivo.

### ISSUE THREAD

**Issue by pedro1958** [phonegap/phonegap-app-developer#524]
Hola mi celular es un alcatel pixi 4 (5) 5045G, no puedo instalar en el phonegap, en google play indica que "Esta app no es compatible con tu dispositivo."
Que debo hacer para instalarlo.
Gracias

**Comment by pedro1958** [comment]
This app is not compatible with your device.
Hello my cell phone is an alcatel pixi 4 (5) 5045G, I can not install in the phonegap, in google play indicates that "This app is not compatible with your device."
What should I do to install it?
Thank you

**Comment by purplecabbage** [comment]
Are you able to install other apps from the playstore?
What version are you trying to install? What Android OS version are you running?
Please reopen with the details, and we'll try to help.
