### ISSUE TITLE
LESS is no longer recompiled during build

### ISSUE THREAD

**Issue by lorenzodallavecchia** [phonegap/phonegap-app-developer#525]
Commit aa23d69ea5920978d3efcac800833084efd61000 removed the `compile-less.js` hook reference in `config.xml`. Was that done on purpose? Looks like a mistake to me.

The LESS files are currently never recompiled, unless you call `npm run build:less` manually of course.

**Comment by purplecabbage** [comment]
Yes this looks like an oversight.
This entire build process will be changing shortly, so I think this is a non issue. Thanks for pointing it out.
