### ISSUE TITLE
Default source code lacks dependencies for compilation

### ISSUE THREAD

**Issue by kcallow** [phonegap/phonegap-app-developer#526]
Hi! I just cloned your repo and I'm compiling Phonegap Developer for Android.
I use an Ubuntu derivative (elementary).

When compiling for Android, I got error messages (summarized):
```
$ npm run phonegap -- run android
Error: Cannot find module 'fs-extra'
$ npm i fs-extra
$ npm run phonegap -- run android
Error: Cannot find module 'app-root-path'
$ npm i app-root-path
$ npm run phonegap -- run android
> node ./resources/script/setup-directories.js
sh: 1: phonegap: not found
$ sudo npm i -g phonegap
$ npm run phonegap -- run android
Android project created with cordova-android@6.4.0
```
So please add the dependencies: fs-extra, app-root-path.
And the README may be misleading: "This means that there is no need for a global installation of phonegap or cordova."  A global installation seems to be required to compile, at least for me...

Thank you for the quality software! I'm excited to hack awesome things with it!
_-kc_

**Comment by surajpindoria** [comment]
Hi @kcallow,

Both of those dependencies are already included in the package.json. If you look at the [Setup](https://github.com/phonegap/phonegap-app-developer#setup) section of the README it does mention that you need to run `npm install` once you clone the repo down.
