### ISSUE TITLE
Phonegap run android doesnt work on devices

### ISSUE THREAD

**Issue by alannaidon** [phonegap/phonegap-app-developer#530]
Hello everyone !
I'm using **phonegap v8.0.0.0**
I did everything I could find on the internet and yet I Can't run my app on my smartphone.  
Everytime I run: 

`phonegap run android` or `phonegap run android --target=XXXX`. 

I get this output: 

`[phonegap] executing 'cordova run android' ...  
[phonegap] completed 'cordova run android --no-telemetry'`

And nothing happens. Nothing is shown on my device.  
`adb devices` shows my devices . USB debugging is activated. I think the problem lays on my pc end, but I can't find anything wrong.

I tried to build/rebuild, remove/add android. Nothing works.

**Comment by EmeryP** [comment]
This might be silly but did you allow PhoneGap access through your PC firewall?

**Comment by maverickmishra** [comment]
This is an issue for the [phonegap-cli](https://github.com/phonegap/phonegap-cli) repo. To answer your question, have you tried `phonegap run android --verbose` to find the error ?
