### ISSUE TITLE
<meta http-equiv="Content-Security-Policy" ... needs to be on own line or blank screen

### ISSUE THREAD

**Issue by travisdahl** [phonegap/phonegap-app-developer#535]
After some very frustrating trial and error I realized that if you dont put `<meta http-equiv="Content-Security-Policy" ... />` on its own line, you will get a blnk screen when trying to preview in the app.

My index is generated as part of a build process that removes all the blank line breaks and this causes it to not work. If i manually break it to its own line, it then works.

doesnt work
```
...<meta name="theme-color" content="#000000"><meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-eval' 'unsafe-inline'; style-src * 'unsafe-inline'; media-src *"/><link rel="stylesheet"...
```

works
```
<meta name="theme-color" content="#000000">
  <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-eval' 'unsafe-inline'; style-src * 'unsafe-inline'; media-src *"/>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"><link rel="stylesheet"...
```

**Comment by purplecabbage** [comment]
What is your build process?  Is it something in phonegap? or is this related to some other webpack/parcel type systems?
I am closing assuming this is not a phonegap thing, please reopen if it is.
