### ISSUE TITLE
How i can preview app in mobile?

### ISSUE THREAD

**Issue by Namrata-1995** [phonegap/phonegap-app-developer#536]
Hi,
     Firstly i created my app in phonegap then i run in browser , it runs properly but i trying to preview app in mobile that time it shows connected and downloading but not download. Please anyone help me to solve this issue.

**Comment by purplecabbage** [comment]
How are you running the app in the browser? Using the CLI?
Are you trying to see the app run by serving it or building it?
Please reopen with more details.
