### ISSUE TITLE
When making changes to the page, the app goes white

### ISSUE THREAD

**Issue by EcoGames** [phonegap/phonegap-app-developer#555]
The only code I've changed was in the index.html file where I added some `<h1>`'s to see if it would work. On the desktop when I go to the link it works fine and it refreshes but the android app just turns white. I've tried restarting the server and my phone. I've closed and reopened the android app many times and I still can't get it to work.

**Comment by JuliePretzlaff** [comment]
I am having the same issue.  The first time I opened the Phonegap App it correctly displayed my hello world project.  When I changed some text in the <h1> and saved, my browser reflected the new change but on android the screen turned to a blank white screen.  Uninstalling the app and reinstalling it, restarting, re-starting server, re-connecting to server has not helped.

**Comment by purplecabbage** [comment]
Closing because there are insufficient details.
Please connect to the app with chrome dev tools and share the error output from the console.
Reopen this issue if you have more details. Thanks.
