### ISSUE TITLE
Cross-Origin Requests Fail

### ISSUE THREAD

**Issue by saniyusuf** [phonegap/phonegap-app-developer#98]
It seems the get request that otherwise work fine when i work  directly with the IDE deployment fails on the Phonegap app. 
I am using Ionic framwork BDW

**Comment by TudorStegarescu** [comment]
any updates???

**Comment by biskis** [comment]
Hi. Does it exists a fix for this? I am using phonegap 5.5.2 and testing in browser. 

Using cli phonegap server.

If I make a ajax call and check Network tab in Chrome I can see that the request is to 192.168.1.92:3000/proxy/[my_url_encoded]

So I think the problem it's not resolved yet or am I missing something that can fix this?

I am on ubuntu 15.10
Thanks.

**Comment by StevenHu** [comment]
I don't know.

Regards,
Steve H

**Comment by meiryu100** [comment]
...

**Comment by meiryu100** [comment]
@biskis  I have the same problem...

**Comment by meiryu100** [comment]
any Idea about this http://localhost:3000/proxy/... my url encoded...

How can I post a normal request... It's must be eas, because everybody wants to save data,
to his database...

Phonegap didn't think about server ?

**Comment by biskis** [comment]
@meiryu100 A solution to this is to install cordova and run: cordova serve in the same place you run phonegap serve
There is no autoreload in cordova (or I didn't see the command for this).

Everything else probably should work ok.

**Comment by meiryu100** [comment]
Thanks dude, you are awesome, do you have any advise for version of cordova ? or a link to download it ?

**Comment by biskis** [comment]
I have latest version of cordova: 6.0.0
You can install from npm: `$ sudo npm install -g cordova`
[Cordova doc](https://cordova.apache.org/docs/en/latest/guide/cli/index.html#installing-the-cordova-cli)

**Comment by meiryu100** [comment]
phonegap serve ? 
I am using the desktop phonegap.. not the cli, 
Do you know where the phonegap should be ?

in the windows?

**Comment by meiryu100** [comment]
I install it on c:/
and phonegap..
program filesx86/adobe/phonegap 

I have windows 10

**Comment by biskis** [comment]
@meiryu100 cordova or phonegap both should be installed globably.
C:\>npm install -g cordova
-g it's for installing globably.

If you have problems follow the steps from here: https://cordova.apache.org/docs/en/latest/guide/cli/index.html#installing-the-cordova-cli

After you installed cordova go to your app folder and run cordova server. This should print to cmd line a url where you can access the app. 
You can't use Phonegap mobile app with cordova.

**Comment by meiryu100** [comment]
So phonegap and cordova this is 2 different things ?
but cordova is also has a server and for mobile and phonegap no have server ?

**Comment by meiryu100** [comment]
ok I install cordova on my comp and the post is working :)...

now do you know maybe, how can I get a login fb ?

**Comment by biskis** [comment]
@meiryu100 No, that's not the difference between phonegap and cordova. Please read this post to undersand better why there is phonegap and cordova: http://phonegap.com/2012/03/19/phonegap-cordova-and-what%E2%80%99s-in-a-name/
Phonegap is under Adobe
Cordova is unde Apache

But both do almost same think. In both should work server comunication. This is not related to this bug.


For facebook login you can use a plugin:
https://github.com/phonegap-build/FacebookConnect/blob/962eb0a1c07935ff813e28aa9eaa5581f2e10416/README.md
https://build.phonegap.com/plugins/257

I didn't implement that but it looks very easy to do. Read the doc.

**Comment by meiryu100** [comment]
OK THANKS
