### ISSUE TITLE
Google Play shows Polaroid Android 4.1.1 as incompatible

### ISSUE THREAD

**Issue by istudiomobile** [phonegap/phonegap-app-developer#99]
Hello,

Congratulations to the PhoneGap Team for such useful tool, however when looking for it to install in my Android tablet it isn't available. Google Play says my device is not compatible.

It would be good to be able to install on tablets as well, as many games are only available for tablets and it will definitely speed up my dev time.

Thank you, your help will be appreciated!

Tablet: Polaroid PMID702DC Android 4.1.1

**Comment by salvisb** [comment]
Hi!
Sorry, I didn't  really got it. How do I install PhoneGap Developer manually from given URL (http://tinyurl.com/motth72). After downloading zip file, what's next? How do I install?

**Comment by surajpindoria** [comment]
Hi @salvisb,

That link above is to an older version of the PhoneGap Developer app, [here](https://github.com/phonegap/phonegap-app-developer/blob/master/resources/release/android/PhoneGap-1.7.0-release.apk) is the latest. Open this link in the browser on your device and request to load the Desktop version of the site if it isn't already. Then select `View raw`, this will download the apk to your device. Go to the file viewer and select the file, it will allow you install from there.

You may need to change your security to allow installing apps from different sources.

**Comment by salvisb** [comment]
@surajpindoria Thank you, everything works fine! :)
